// Code generated by sqlc. DO NOT EDIT.

package pg10

import (
	"database/sql"

	"github.com/jackc/pgtype"
)

type PgAggregate struct {
	Aggfnoid         pgtype.Text
	Aggkind          pgtype.QChar
	Aggnumdirectargs int16
	Aggtransfn       pgtype.Text
	Aggfinalfn       pgtype.Text
	Aggcombinefn     pgtype.Text
	Aggserialfn      pgtype.Text
	Aggdeserialfn    pgtype.Text
	Aggmtransfn      pgtype.Text
	Aggminvtransfn   pgtype.Text
	Aggmfinalfn      pgtype.Text
	Aggfinalextra    bool
	Aggmfinalextra   bool
	Aggsortop        pgtype.OID
	Aggtranstype     pgtype.OID
	Aggtransspace    int32
	Aggmtranstype    pgtype.OID
	Aggmtransspace   int32
	Agginitval       pgtype.Text
	Aggminitval      pgtype.Text
}

type PgAm struct {
	Amname    string
	Amhandler pgtype.Text
	Amtype    pgtype.QChar
}

type PgAmop struct {
	Amopfamily     pgtype.OID
	Amoplefttype   pgtype.OID
	Amoprighttype  pgtype.OID
	Amopstrategy   int16
	Amoppurpose    pgtype.QChar
	Amopopr        pgtype.OID
	Amopmethod     pgtype.OID
	Amopsortfamily pgtype.OID
}

type PgAmproc struct {
	Amprocfamily    pgtype.OID
	Amproclefttype  pgtype.OID
	Amprocrighttype pgtype.OID
	Amprocnum       int16
	Amproc          pgtype.Text
}

type PgAttrdef struct {
	Adrelid pgtype.OID
	Adnum   int16
	Adbin   interface{}
	Adsrc   pgtype.Text
}

type PgAttribute struct {
	Attrelid      pgtype.OID
	Attname       string
	Atttypid      pgtype.OID
	Attstattarget int32
	Attlen        int16
	Attnum        int16
	Attndims      int32
	Attcacheoff   int32
	Atttypmod     int32
	Attbyval      bool
	Attstorage    pgtype.QChar
	Attalign      pgtype.QChar
	Attnotnull    bool
	Atthasdef     bool
	Attidentity   pgtype.QChar
	Attisdropped  bool
	Attislocal    bool
	Attinhcount   int32
	Attcollation  pgtype.OID
	Attacl        []pgtype.ACLItem
	Attoptions    []pgtype.Text
	Attfdwoptions []pgtype.Text
}

type PgAuthMembers struct {
	Roleid      pgtype.OID
	Member      pgtype.OID
	Grantor     pgtype.OID
	AdminOption bool
}

type PgAuthid struct {
	Rolname        string
	Rolsuper       bool
	Rolinherit     bool
	Rolcreaterole  bool
	Rolcreatedb    bool
	Rolcanlogin    bool
	Rolreplication bool
	Rolbypassrls   bool
	Rolconnlimit   int32
	Rolpassword    pgtype.Text
	Rolvaliduntil  sql.NullTime
}

type PgAvailableExtensionVersions struct {
	Name        pgtype.Name
	Version     pgtype.Text
	Installed   sql.NullBool
	Superuser   sql.NullBool
	Relocatable sql.NullBool
	Schema      pgtype.Name
	Requires    []string
	Comment     pgtype.Text
}

type PgAvailableExtensions struct {
	Name             pgtype.Name
	DefaultVersion   pgtype.Text
	InstalledVersion pgtype.Text
	Comment          pgtype.Text
}

type PgCast struct {
	Castsource  pgtype.OID
	Casttarget  pgtype.OID
	Castfunc    pgtype.OID
	Castcontext pgtype.QChar
	Castmethod  pgtype.QChar
}

type PgClass struct {
	Relname             string
	Relnamespace        pgtype.OID
	Reltype             pgtype.OID
	Reloftype           pgtype.OID
	Relowner            pgtype.OID
	Relam               pgtype.OID
	Relfilenode         pgtype.OID
	Reltablespace       pgtype.OID
	Relpages            int32
	Reltuples           float32
	Relallvisible       int32
	Reltoastrelid       pgtype.OID
	Relhasindex         bool
	Relisshared         bool
	Relpersistence      pgtype.QChar
	Relkind             pgtype.QChar
	Relnatts            int16
	Relchecks           int16
	Relhasoids          bool
	Relhaspkey          bool
	Relhasrules         bool
	Relhastriggers      bool
	Relhassubclass      bool
	Relrowsecurity      bool
	Relforcerowsecurity bool
	Relispopulated      bool
	Relreplident        pgtype.QChar
	Relispartition      bool
	Relfrozenxid        pgtype.XID
	Relminmxid          pgtype.XID
	Relacl              []pgtype.ACLItem
	Reloptions          []pgtype.Text
	Relpartbound        interface{}
}

type PgCollation struct {
	Collname      string
	Collnamespace pgtype.OID
	Collowner     pgtype.OID
	Collprovider  pgtype.QChar
	Collencoding  int32
	Collcollate   string
	Collctype     string
	Collversion   pgtype.Text
}

type PgConfig struct {
	Name    pgtype.Text
	Setting pgtype.Text
}

type PgConstraint struct {
	Conname       string
	Connamespace  pgtype.OID
	Contype       pgtype.QChar
	Condeferrable bool
	Condeferred   bool
	Convalidated  bool
	Conrelid      pgtype.OID
	Contypid      pgtype.OID
	Conindid      pgtype.OID
	Confrelid     pgtype.OID
	Confupdtype   pgtype.QChar
	Confdeltype   pgtype.QChar
	Confmatchtype pgtype.QChar
	Conislocal    bool
	Coninhcount   int32
	Connoinherit  bool
	Conkey        []int16
	Confkey       []int16
	Conpfeqop     []pgtype.OID
	Conppeqop     []pgtype.OID
	Conffeqop     []pgtype.OID
	Conexclop     []pgtype.OID
	Conbin        interface{}
	Consrc        pgtype.Text
}

type PgConversion struct {
	Conname        string
	Connamespace   pgtype.OID
	Conowner       pgtype.OID
	Conforencoding int32
	Contoencoding  int32
	Conproc        pgtype.Text
	Condefault     bool
}

type PgCursors struct {
	Name         pgtype.Text
	Statement    pgtype.Text
	IsHoldable   sql.NullBool
	IsBinary     sql.NullBool
	IsScrollable sql.NullBool
	CreationTime sql.NullTime
}

type PgDatabase struct {
	Datname       string
	Datdba        pgtype.OID
	Encoding      int32
	Datcollate    string
	Datctype      string
	Datistemplate bool
	Datallowconn  bool
	Datconnlimit  int32
	Datlastsysoid pgtype.OID
	Datfrozenxid  pgtype.XID
	Datminmxid    pgtype.XID
	Dattablespace pgtype.OID
	Datacl        []pgtype.ACLItem
}

type PgDbRoleSetting struct {
	Setdatabase pgtype.OID
	Setrole     pgtype.OID
	Setconfig   []pgtype.Text
}

type PgDefaultAcl struct {
	Defaclrole      pgtype.OID
	Defaclnamespace pgtype.OID
	Defaclobjtype   pgtype.QChar
	Defaclacl       []pgtype.ACLItem
}

type PgDepend struct {
	Classid     pgtype.OID
	Objid       pgtype.OID
	Objsubid    int32
	Refclassid  pgtype.OID
	Refobjid    pgtype.OID
	Refobjsubid int32
	Deptype     pgtype.QChar
}

type PgDescription struct {
	Objoid      pgtype.OID
	Classoid    pgtype.OID
	Objsubid    int32
	Description pgtype.Text
}

type PgEnum struct {
	Enumtypid     pgtype.OID
	Enumsortorder float32
	Enumlabel     string
}

type PgEventTrigger struct {
	Evtname    string
	Evtevent   string
	Evtowner   pgtype.OID
	Evtfoid    pgtype.OID
	Evtenabled pgtype.QChar
	Evttags    []pgtype.Text
}

type PgExtension struct {
	Extname        string
	Extowner       pgtype.OID
	Extnamespace   pgtype.OID
	Extrelocatable bool
	Extversion     pgtype.Text
	Extconfig      []pgtype.OID
	Extcondition   []pgtype.Text
}

type PgFileSettings struct {
	Sourcefile pgtype.Text
	Sourceline sql.NullInt32
	Seqno      sql.NullInt32
	Name       pgtype.Text
	Setting    pgtype.Text
	Applied    sql.NullBool
	Error      pgtype.Text
}

type PgForeignDataWrapper struct {
	Fdwname      string
	Fdwowner     pgtype.OID
	Fdwhandler   pgtype.OID
	Fdwvalidator pgtype.OID
	Fdwacl       []pgtype.ACLItem
	Fdwoptions   []pgtype.Text
}

type PgForeignServer struct {
	Srvname    string
	Srvowner   pgtype.OID
	Srvfdw     pgtype.OID
	Srvtype    pgtype.Text
	Srvversion pgtype.Text
	Srvacl     []pgtype.ACLItem
	Srvoptions []pgtype.Text
}

type PgForeignTable struct {
	Ftrelid   pgtype.OID
	Ftserver  pgtype.OID
	Ftoptions []pgtype.Text
}

type PgGroup struct {
	Groname  pgtype.Name
	Grosysid pgtype.OIDValue
	Grolist  []pgtype.OID
}

type PgHbaFileRules struct {
	LineNumber sql.NullInt32
	Type       pgtype.Text
	Database   []pgtype.Text
	UserName   []pgtype.Text
	Address    pgtype.Text
	Netmask    pgtype.Text
	AuthMethod pgtype.Text
	Options    []pgtype.Text
	Error      pgtype.Text
}

type PgIndex struct {
	Indexrelid     pgtype.OID
	Indrelid       pgtype.OID
	Indnatts       int16
	Indisunique    bool
	Indisprimary   bool
	Indisexclusion bool
	Indimmediate   bool
	Indisclustered bool
	Indisvalid     bool
	Indcheckxmin   bool
	Indisready     bool
	Indislive      bool
	Indisreplident bool
	Indkey         []int16
	Indcollation   []pgtype.OID
	Indclass       []pgtype.OID
	Indoption      []int16
	Indexprs       interface{}
	Indpred        interface{}
}

type PgIndexes struct {
	Schemaname pgtype.Name
	Tablename  pgtype.Name
	Indexname  pgtype.Name
	Tablespace pgtype.Name
	Indexdef   pgtype.Text
}

type PgInherits struct {
	Inhrelid  pgtype.OID
	Inhparent pgtype.OID
	Inhseqno  int32
}

type PgInitPrivs struct {
	Objoid    pgtype.OID
	Classoid  pgtype.OID
	Objsubid  int32
	Privtype  pgtype.QChar
	Initprivs []pgtype.ACLItem
}

type PgLanguage struct {
	Lanname       string
	Lanowner      pgtype.OID
	Lanispl       bool
	Lanpltrusted  bool
	Lanplcallfoid pgtype.OID
	Laninline     pgtype.OID
	Lanvalidator  pgtype.OID
	Lanacl        []pgtype.ACLItem
}

type PgLargeobject struct {
	Loid   pgtype.OID
	Pageno int32
	Data   pgtype.Bytea
}

type PgLargeobjectMetadata struct {
	Lomowner pgtype.OID
	Lomacl   []pgtype.ACLItem
}

type PgLocks struct {
	Locktype           pgtype.Text
	Database           pgtype.OIDValue
	Relation           pgtype.OIDValue
	Page               sql.NullInt32
	Tuple              int16
	Virtualxid         pgtype.Text
	Transactionid      pgtype.XID
	Classid            pgtype.OIDValue
	Objid              pgtype.OIDValue
	Objsubid           int16
	Virtualtransaction pgtype.Text
	Pid                sql.NullInt32
	Mode               pgtype.Text
	Granted            sql.NullBool
	Fastpath           sql.NullBool
}

type PgMatviews struct {
	Schemaname   pgtype.Name
	Matviewname  pgtype.Name
	Matviewowner pgtype.Name
	Tablespace   pgtype.Name
	Hasindexes   sql.NullBool
	Ispopulated  sql.NullBool
	Definition   pgtype.Text
}

type PgNamespace struct {
	Nspname  string
	Nspowner pgtype.OID
	Nspacl   []pgtype.ACLItem
}

type PgOpclass struct {
	Opcmethod    pgtype.OID
	Opcname      string
	Opcnamespace pgtype.OID
	Opcowner     pgtype.OID
	Opcfamily    pgtype.OID
	Opcintype    pgtype.OID
	Opcdefault   bool
	Opckeytype   pgtype.OID
}

type PgOperator struct {
	Oprname      string
	Oprnamespace pgtype.OID
	Oprowner     pgtype.OID
	Oprkind      pgtype.QChar
	Oprcanmerge  bool
	Oprcanhash   bool
	Oprleft      pgtype.OID
	Oprright     pgtype.OID
	Oprresult    pgtype.OID
	Oprcom       pgtype.OID
	Oprnegate    pgtype.OID
	Oprcode      pgtype.Text
	Oprrest      pgtype.Text
	Oprjoin      pgtype.Text
}

type PgOpfamily struct {
	Opfmethod    pgtype.OID
	Opfname      string
	Opfnamespace pgtype.OID
	Opfowner     pgtype.OID
}

type PgPartitionedTable struct {
	Partrelid     pgtype.OID
	Partstrat     pgtype.QChar
	Partnatts     int16
	Partattrs     []int16
	Partclass     []pgtype.OID
	Partcollation []pgtype.OID
	Partexprs     interface{}
}

type PgPltemplate struct {
	Tmplname      string
	Tmpltrusted   bool
	Tmpldbacreate bool
	Tmplhandler   pgtype.Text
	Tmplinline    pgtype.Text
	Tmplvalidator pgtype.Text
	Tmpllibrary   pgtype.Text
	Tmplacl       []pgtype.ACLItem
}

type PgPolicies struct {
	Schemaname pgtype.Name
	Tablename  pgtype.Name
	Policyname pgtype.Name
	Permissive pgtype.Text
	Roles      []string
	Cmd        pgtype.Text
	Qual       pgtype.Text
	WithCheck  pgtype.Text
}

type PgPolicy struct {
	Polname       string
	Polrelid      pgtype.OID
	Polcmd        pgtype.QChar
	Polpermissive bool
	Polroles      []pgtype.OID
	Polqual       interface{}
	Polwithcheck  interface{}
}

type PgPreparedStatements struct {
	Name           pgtype.Text
	Statement      pgtype.Text
	PrepareTime    sql.NullTime
	ParameterTypes []pgtype.Text
	FromSql        sql.NullBool
}

type PgPreparedXacts struct {
	Transaction pgtype.XID
	Gid         pgtype.Text
	Prepared    sql.NullTime
	Owner       pgtype.Name
	Database    pgtype.Name
}

type PgProc struct {
	Proname         string
	Pronamespace    pgtype.OID
	Proowner        pgtype.OID
	Prolang         pgtype.OID
	Procost         float32
	Prorows         float32
	Provariadic     pgtype.OID
	Protransform    pgtype.Text
	Proisagg        bool
	Proiswindow     bool
	Prosecdef       bool
	Proleakproof    bool
	Proisstrict     bool
	Proretset       bool
	Provolatile     pgtype.QChar
	Proparallel     pgtype.QChar
	Pronargs        int16
	Pronargdefaults int16
	Prorettype      pgtype.OID
	Proargtypes     []pgtype.OID
	Proallargtypes  []pgtype.OID
	Proargmodes     []pgtype.QChar
	Proargnames     []pgtype.Text
	Proargdefaults  interface{}
	Protrftypes     []pgtype.OID
	Prosrc          pgtype.Text
	Probin          pgtype.Text
	Proconfig       []pgtype.Text
	Proacl          []pgtype.ACLItem
}

type PgPublication struct {
	Pubname      string
	Pubowner     pgtype.OID
	Puballtables bool
	Pubinsert    bool
	Pubupdate    bool
	Pubdelete    bool
}

type PgPublicationRel struct {
	Prpubid pgtype.OID
	Prrelid pgtype.OID
}

type PgPublicationTables struct {
	Pubname    pgtype.Name
	Schemaname pgtype.Name
	Tablename  pgtype.Name
}

type PgRange struct {
	Rngtypid     pgtype.OID
	Rngsubtype   pgtype.OID
	Rngcollation pgtype.OID
	Rngsubopc    pgtype.OID
	Rngcanonical pgtype.Text
	Rngsubdiff   pgtype.Text
}

type PgReplicationOrigin struct {
	Roident pgtype.OID
	Roname  pgtype.Text
}

type PgReplicationOriginStatus struct {
	LocalID    pgtype.OIDValue
	ExternalID pgtype.Text
	RemoteLsn  interface{}
	LocalLsn   interface{}
}

type PgReplicationSlots struct {
	SlotName          pgtype.Name
	Plugin            pgtype.Name
	SlotType          pgtype.Text
	Datoid            pgtype.OIDValue
	Database          pgtype.Name
	Temporary         sql.NullBool
	Active            sql.NullBool
	ActivePid         sql.NullInt32
	Xmin              pgtype.XID
	CatalogXmin       pgtype.XID
	RestartLsn        interface{}
	ConfirmedFlushLsn interface{}
}

type PgRewrite struct {
	Rulename  string
	EvClass   pgtype.OID
	EvType    pgtype.QChar
	EvEnabled pgtype.QChar
	IsInstead bool
	EvQual    interface{}
	EvAction  interface{}
}

type PgRoles struct {
	Rolname        pgtype.Name
	Rolsuper       sql.NullBool
	Rolinherit     sql.NullBool
	Rolcreaterole  sql.NullBool
	Rolcreatedb    sql.NullBool
	Rolcanlogin    sql.NullBool
	Rolreplication sql.NullBool
	Rolconnlimit   sql.NullInt32
	Rolpassword    pgtype.Text
	Rolvaliduntil  sql.NullTime
	Rolbypassrls   sql.NullBool
	Rolconfig      []pgtype.Text
	Oid            pgtype.OIDValue
}

type PgRules struct {
	Schemaname pgtype.Name
	Tablename  pgtype.Name
	Rulename   pgtype.Name
	Definition pgtype.Text
}

type PgSeclabel struct {
	Objoid   pgtype.OID
	Classoid pgtype.OID
	Objsubid int32
	Provider pgtype.Text
	Label    pgtype.Text
}

type PgSeclabels struct {
	Objoid       pgtype.OIDValue
	Classoid     pgtype.OIDValue
	Objsubid     sql.NullInt32
	Objtype      pgtype.Text
	Objnamespace pgtype.OIDValue
	Objname      pgtype.Text
	Provider     pgtype.Text
	Label        pgtype.Text
}

type PgSequence struct {
	Seqrelid     pgtype.OID
	Seqtypid     pgtype.OID
	Seqstart     int64
	Seqincrement int64
	Seqmax       int64
	Seqmin       int64
	Seqcache     int64
	Seqcycle     bool
}

type PgSequences struct {
	Schemaname    pgtype.Name
	Sequencename  pgtype.Name
	Sequenceowner pgtype.Name
	DataType      pgtype.Text
	StartValue    sql.NullInt64
	MinValue      sql.NullInt64
	MaxValue      sql.NullInt64
	IncrementBy   sql.NullInt64
	Cycle         sql.NullBool
	CacheSize     sql.NullInt64
	LastValue     sql.NullInt64
}

type PgSettings struct {
	Name           pgtype.Text
	Setting        pgtype.Text
	Unit           pgtype.Text
	Category       pgtype.Text
	ShortDesc      pgtype.Text
	ExtraDesc      pgtype.Text
	Context        pgtype.Text
	Vartype        pgtype.Text
	Source         pgtype.Text
	MinVal         pgtype.Text
	MaxVal         pgtype.Text
	Enumvals       []pgtype.Text
	BootVal        pgtype.Text
	ResetVal       pgtype.Text
	Sourcefile     pgtype.Text
	Sourceline     sql.NullInt32
	PendingRestart sql.NullBool
}

type PgShadow struct {
	Usename      pgtype.Name
	Usesysid     pgtype.OIDValue
	Usecreatedb  sql.NullBool
	Usesuper     sql.NullBool
	Userepl      sql.NullBool
	Usebypassrls sql.NullBool
	Passwd       pgtype.Text
	Valuntil     interface{}
	Useconfig    []pgtype.Text
}

type PgShdepend struct {
	Dbid       pgtype.OID
	Classid    pgtype.OID
	Objid      pgtype.OID
	Objsubid   int32
	Refclassid pgtype.OID
	Refobjid   pgtype.OID
	Deptype    pgtype.QChar
}

type PgShdescription struct {
	Objoid      pgtype.OID
	Classoid    pgtype.OID
	Description pgtype.Text
}

type PgShseclabel struct {
	Objoid   pgtype.OID
	Classoid pgtype.OID
	Provider pgtype.Text
	Label    pgtype.Text
}

type PgStatActivity struct {
	Datid           pgtype.OIDValue
	Datname         pgtype.Name
	Pid             sql.NullInt32
	Usesysid        pgtype.OIDValue
	Usename         pgtype.Name
	ApplicationName pgtype.Text
	ClientAddr      pgtype.Inet
	ClientHostname  pgtype.Text
	ClientPort      sql.NullInt32
	BackendStart    sql.NullTime
	XactStart       sql.NullTime
	QueryStart      sql.NullTime
	StateChange     sql.NullTime
	WaitEventType   pgtype.Text
	WaitEvent       pgtype.Text
	State           pgtype.Text
	BackendXid      pgtype.XID
	BackendXmin     pgtype.XID
	Query           pgtype.Text
	BackendType     pgtype.Text
}

type PgStatAllIndexes struct {
	Relid        pgtype.OIDValue
	Indexrelid   pgtype.OIDValue
	Schemaname   pgtype.Name
	Relname      pgtype.Name
	Indexrelname pgtype.Name
	IdxScan      sql.NullInt64
	IdxTupRead   sql.NullInt64
	IdxTupFetch  sql.NullInt64
}

type PgStatAllTables struct {
	Relid            pgtype.OIDValue
	Schemaname       pgtype.Name
	Relname          pgtype.Name
	SeqScan          sql.NullInt64
	SeqTupRead       sql.NullInt64
	IdxScan          sql.NullInt64
	IdxTupFetch      sql.NullInt64
	NTupIns          sql.NullInt64
	NTupUpd          sql.NullInt64
	NTupDel          sql.NullInt64
	NTupHotUpd       sql.NullInt64
	NLiveTup         sql.NullInt64
	NDeadTup         sql.NullInt64
	NModSinceAnalyze sql.NullInt64
	LastVacuum       sql.NullTime
	LastAutovacuum   sql.NullTime
	LastAnalyze      sql.NullTime
	LastAutoanalyze  sql.NullTime
	VacuumCount      sql.NullInt64
	AutovacuumCount  sql.NullInt64
	AnalyzeCount     sql.NullInt64
	AutoanalyzeCount sql.NullInt64
}

type PgStatArchiver struct {
	ArchivedCount    sql.NullInt64
	LastArchivedWal  pgtype.Text
	LastArchivedTime sql.NullTime
	FailedCount      sql.NullInt64
	LastFailedWal    pgtype.Text
	LastFailedTime   sql.NullTime
	StatsReset       sql.NullTime
}

type PgStatBgwriter struct {
	CheckpointsTimed    sql.NullInt64
	CheckpointsReq      sql.NullInt64
	CheckpointWriteTime sql.NullFloat64
	CheckpointSyncTime  sql.NullFloat64
	BuffersCheckpoint   sql.NullInt64
	BuffersClean        sql.NullInt64
	MaxwrittenClean     sql.NullInt64
	BuffersBackend      sql.NullInt64
	BuffersBackendFsync sql.NullInt64
	BuffersAlloc        sql.NullInt64
	StatsReset          sql.NullTime
}

type PgStatDatabase struct {
	Datid        pgtype.OIDValue
	Datname      pgtype.Name
	Numbackends  sql.NullInt32
	XactCommit   sql.NullInt64
	XactRollback sql.NullInt64
	BlksRead     sql.NullInt64
	BlksHit      sql.NullInt64
	TupReturned  sql.NullInt64
	TupFetched   sql.NullInt64
	TupInserted  sql.NullInt64
	TupUpdated   sql.NullInt64
	TupDeleted   sql.NullInt64
	Conflicts    sql.NullInt64
	TempFiles    sql.NullInt64
	TempBytes    sql.NullInt64
	Deadlocks    sql.NullInt64
	BlkReadTime  sql.NullFloat64
	BlkWriteTime sql.NullFloat64
	StatsReset   sql.NullTime
}

type PgStatDatabaseConflicts struct {
	Datid           pgtype.OIDValue
	Datname         pgtype.Name
	ConflTablespace sql.NullInt64
	ConflLock       sql.NullInt64
	ConflSnapshot   sql.NullInt64
	ConflBufferpin  sql.NullInt64
	ConflDeadlock   sql.NullInt64
}

type PgStatProgressVacuum struct {
	Pid              sql.NullInt32
	Datid            pgtype.OIDValue
	Datname          pgtype.Name
	Relid            pgtype.OIDValue
	Phase            pgtype.Text
	HeapBlksTotal    sql.NullInt64
	HeapBlksScanned  sql.NullInt64
	HeapBlksVacuumed sql.NullInt64
	IndexVacuumCount sql.NullInt64
	MaxDeadTuples    sql.NullInt64
	NumDeadTuples    sql.NullInt64
}

type PgStatReplication struct {
	Pid             sql.NullInt32
	Usesysid        pgtype.OIDValue
	Usename         pgtype.Name
	ApplicationName pgtype.Text
	ClientAddr      pgtype.Inet
	ClientHostname  pgtype.Text
	ClientPort      sql.NullInt32
	BackendStart    sql.NullTime
	BackendXmin     pgtype.XID
	State           pgtype.Text
	SentLsn         interface{}
	WriteLsn        interface{}
	FlushLsn        interface{}
	ReplayLsn       interface{}
	WriteLag        sql.NullInt64
	FlushLag        sql.NullInt64
	ReplayLag       sql.NullInt64
	SyncPriority    sql.NullInt32
	SyncState       pgtype.Text
}

type PgStatSsl struct {
	Pid         sql.NullInt32
	Ssl         sql.NullBool
	Version     pgtype.Text
	Cipher      pgtype.Text
	Bits        sql.NullInt32
	Compression sql.NullBool
	Clientdn    pgtype.Text
}

type PgStatSubscription struct {
	Subid              pgtype.OIDValue
	Subname            pgtype.Name
	Pid                sql.NullInt32
	Relid              pgtype.OIDValue
	ReceivedLsn        interface{}
	LastMsgSendTime    sql.NullTime
	LastMsgReceiptTime sql.NullTime
	LatestEndLsn       interface{}
	LatestEndTime      sql.NullTime
}

type PgStatSysIndexes struct {
	Relid        pgtype.OIDValue
	Indexrelid   pgtype.OIDValue
	Schemaname   pgtype.Name
	Relname      pgtype.Name
	Indexrelname pgtype.Name
	IdxScan      sql.NullInt64
	IdxTupRead   sql.NullInt64
	IdxTupFetch  sql.NullInt64
}

type PgStatSysTables struct {
	Relid            pgtype.OIDValue
	Schemaname       pgtype.Name
	Relname          pgtype.Name
	SeqScan          sql.NullInt64
	SeqTupRead       sql.NullInt64
	IdxScan          sql.NullInt64
	IdxTupFetch      sql.NullInt64
	NTupIns          sql.NullInt64
	NTupUpd          sql.NullInt64
	NTupDel          sql.NullInt64
	NTupHotUpd       sql.NullInt64
	NLiveTup         sql.NullInt64
	NDeadTup         sql.NullInt64
	NModSinceAnalyze sql.NullInt64
	LastVacuum       sql.NullTime
	LastAutovacuum   sql.NullTime
	LastAnalyze      sql.NullTime
	LastAutoanalyze  sql.NullTime
	VacuumCount      sql.NullInt64
	AutovacuumCount  sql.NullInt64
	AnalyzeCount     sql.NullInt64
	AutoanalyzeCount sql.NullInt64
}

type PgStatUserFunctions struct {
	Funcid     pgtype.OIDValue
	Schemaname pgtype.Name
	Funcname   pgtype.Name
	Calls      sql.NullInt64
	TotalTime  sql.NullFloat64
	SelfTime   sql.NullFloat64
}

type PgStatUserIndexes struct {
	Relid        pgtype.OIDValue
	Indexrelid   pgtype.OIDValue
	Schemaname   pgtype.Name
	Relname      pgtype.Name
	Indexrelname pgtype.Name
	IdxScan      sql.NullInt64
	IdxTupRead   sql.NullInt64
	IdxTupFetch  sql.NullInt64
}

type PgStatUserTables struct {
	Relid            pgtype.OIDValue
	Schemaname       pgtype.Name
	Relname          pgtype.Name
	SeqScan          sql.NullInt64
	SeqTupRead       sql.NullInt64
	IdxScan          sql.NullInt64
	IdxTupFetch      sql.NullInt64
	NTupIns          sql.NullInt64
	NTupUpd          sql.NullInt64
	NTupDel          sql.NullInt64
	NTupHotUpd       sql.NullInt64
	NLiveTup         sql.NullInt64
	NDeadTup         sql.NullInt64
	NModSinceAnalyze sql.NullInt64
	LastVacuum       sql.NullTime
	LastAutovacuum   sql.NullTime
	LastAnalyze      sql.NullTime
	LastAutoanalyze  sql.NullTime
	VacuumCount      sql.NullInt64
	AutovacuumCount  sql.NullInt64
	AnalyzeCount     sql.NullInt64
	AutoanalyzeCount sql.NullInt64
}

type PgStatWalReceiver struct {
	Pid                sql.NullInt32
	Status             pgtype.Text
	ReceiveStartLsn    interface{}
	ReceiveStartTli    sql.NullInt32
	ReceivedLsn        interface{}
	ReceivedTli        sql.NullInt32
	LastMsgSendTime    sql.NullTime
	LastMsgReceiptTime sql.NullTime
	LatestEndLsn       interface{}
	LatestEndTime      sql.NullTime
	SlotName           pgtype.Text
	Conninfo           pgtype.Text
}

type PgStatXactAllTables struct {
	Relid       pgtype.OIDValue
	Schemaname  pgtype.Name
	Relname     pgtype.Name
	SeqScan     sql.NullInt64
	SeqTupRead  sql.NullInt64
	IdxScan     sql.NullInt64
	IdxTupFetch sql.NullInt64
	NTupIns     sql.NullInt64
	NTupUpd     sql.NullInt64
	NTupDel     sql.NullInt64
	NTupHotUpd  sql.NullInt64
}

type PgStatXactSysTables struct {
	Relid       pgtype.OIDValue
	Schemaname  pgtype.Name
	Relname     pgtype.Name
	SeqScan     sql.NullInt64
	SeqTupRead  sql.NullInt64
	IdxScan     sql.NullInt64
	IdxTupFetch sql.NullInt64
	NTupIns     sql.NullInt64
	NTupUpd     sql.NullInt64
	NTupDel     sql.NullInt64
	NTupHotUpd  sql.NullInt64
}

type PgStatXactUserFunctions struct {
	Funcid     pgtype.OIDValue
	Schemaname pgtype.Name
	Funcname   pgtype.Name
	Calls      sql.NullInt64
	TotalTime  sql.NullFloat64
	SelfTime   sql.NullFloat64
}

type PgStatXactUserTables struct {
	Relid       pgtype.OIDValue
	Schemaname  pgtype.Name
	Relname     pgtype.Name
	SeqScan     sql.NullInt64
	SeqTupRead  sql.NullInt64
	IdxScan     sql.NullInt64
	IdxTupFetch sql.NullInt64
	NTupIns     sql.NullInt64
	NTupUpd     sql.NullInt64
	NTupDel     sql.NullInt64
	NTupHotUpd  sql.NullInt64
}

type PgStatioAllIndexes struct {
	Relid        pgtype.OIDValue
	Indexrelid   pgtype.OIDValue
	Schemaname   pgtype.Name
	Relname      pgtype.Name
	Indexrelname pgtype.Name
	IdxBlksRead  sql.NullInt64
	IdxBlksHit   sql.NullInt64
}

type PgStatioAllSequences struct {
	Relid      pgtype.OIDValue
	Schemaname pgtype.Name
	Relname    pgtype.Name
	BlksRead   sql.NullInt64
	BlksHit    sql.NullInt64
}

type PgStatioAllTables struct {
	Relid         pgtype.OIDValue
	Schemaname    pgtype.Name
	Relname       pgtype.Name
	HeapBlksRead  sql.NullInt64
	HeapBlksHit   sql.NullInt64
	IdxBlksRead   sql.NullInt64
	IdxBlksHit    sql.NullInt64
	ToastBlksRead sql.NullInt64
	ToastBlksHit  sql.NullInt64
	TidxBlksRead  sql.NullInt64
	TidxBlksHit   sql.NullInt64
}

type PgStatioSysIndexes struct {
	Relid        pgtype.OIDValue
	Indexrelid   pgtype.OIDValue
	Schemaname   pgtype.Name
	Relname      pgtype.Name
	Indexrelname pgtype.Name
	IdxBlksRead  sql.NullInt64
	IdxBlksHit   sql.NullInt64
}

type PgStatioSysSequences struct {
	Relid      pgtype.OIDValue
	Schemaname pgtype.Name
	Relname    pgtype.Name
	BlksRead   sql.NullInt64
	BlksHit    sql.NullInt64
}

type PgStatioSysTables struct {
	Relid         pgtype.OIDValue
	Schemaname    pgtype.Name
	Relname       pgtype.Name
	HeapBlksRead  sql.NullInt64
	HeapBlksHit   sql.NullInt64
	IdxBlksRead   sql.NullInt64
	IdxBlksHit    sql.NullInt64
	ToastBlksRead sql.NullInt64
	ToastBlksHit  sql.NullInt64
	TidxBlksRead  sql.NullInt64
	TidxBlksHit   sql.NullInt64
}

type PgStatioUserIndexes struct {
	Relid        pgtype.OIDValue
	Indexrelid   pgtype.OIDValue
	Schemaname   pgtype.Name
	Relname      pgtype.Name
	Indexrelname pgtype.Name
	IdxBlksRead  sql.NullInt64
	IdxBlksHit   sql.NullInt64
}

type PgStatioUserSequences struct {
	Relid      pgtype.OIDValue
	Schemaname pgtype.Name
	Relname    pgtype.Name
	BlksRead   sql.NullInt64
	BlksHit    sql.NullInt64
}

type PgStatioUserTables struct {
	Relid         pgtype.OIDValue
	Schemaname    pgtype.Name
	Relname       pgtype.Name
	HeapBlksRead  sql.NullInt64
	HeapBlksHit   sql.NullInt64
	IdxBlksRead   sql.NullInt64
	IdxBlksHit    sql.NullInt64
	ToastBlksRead sql.NullInt64
	ToastBlksHit  sql.NullInt64
	TidxBlksRead  sql.NullInt64
	TidxBlksHit   sql.NullInt64
}

type PgStatistic struct {
	Starelid    pgtype.OID
	Staattnum   int16
	Stainherit  bool
	Stanullfrac float32
	Stawidth    int32
	Stadistinct float32
	Stakind1    int16
	Stakind2    int16
	Stakind3    int16
	Stakind4    int16
	Stakind5    int16
	Staop1      pgtype.OID
	Staop2      pgtype.OID
	Staop3      pgtype.OID
	Staop4      pgtype.OID
	Staop5      pgtype.OID
	Stanumbers1 []float32
	Stanumbers2 []float32
	Stanumbers3 []float32
	Stanumbers4 []float32
	Stanumbers5 []float32
	Stavalues1  interface{}
	Stavalues2  interface{}
	Stavalues3  interface{}
	Stavalues4  interface{}
	Stavalues5  interface{}
}

type PgStatisticExt struct {
	Stxrelid        pgtype.OID
	Stxname         string
	Stxnamespace    pgtype.OID
	Stxowner        pgtype.OID
	Stxkeys         []int16
	Stxkind         []pgtype.QChar
	Stxndistinct    interface{}
	Stxdependencies interface{}
}

type PgStats struct {
	Schemaname          pgtype.Name
	Tablename           pgtype.Name
	Attname             pgtype.Name
	Inherited           sql.NullBool
	NullFrac            sql.NullFloat64
	AvgWidth            sql.NullInt32
	NDistinct           sql.NullFloat64
	MostCommonVals      interface{}
	MostCommonFreqs     []float32
	HistogramBounds     interface{}
	Correlation         sql.NullFloat64
	MostCommonElems     interface{}
	MostCommonElemFreqs []float32
	ElemCountHistogram  []float32
}

type PgSubscription struct {
	Subdbid         pgtype.OID
	Subname         string
	Subowner        pgtype.OID
	Subenabled      bool
	Subconninfo     pgtype.Text
	Subslotname     string
	Subsynccommit   pgtype.Text
	Subpublications []pgtype.Text
}

type PgSubscriptionRel struct {
	Srsubid    pgtype.OID
	Srrelid    pgtype.OID
	Srsubstate pgtype.QChar
	Srsublsn   interface{}
}

type PgTables struct {
	Schemaname  pgtype.Name
	Tablename   pgtype.Name
	Tableowner  pgtype.Name
	Tablespace  pgtype.Name
	Hasindexes  sql.NullBool
	Hasrules    sql.NullBool
	Hastriggers sql.NullBool
	Rowsecurity sql.NullBool
}

type PgTablespace struct {
	Spcname    string
	Spcowner   pgtype.OID
	Spcacl     []pgtype.ACLItem
	Spcoptions []pgtype.Text
}

type PgTimezoneAbbrevs struct {
	Abbrev    pgtype.Text
	UtcOffset sql.NullInt64
	IsDst     sql.NullBool
}

type PgTimezoneNames struct {
	Name      pgtype.Text
	Abbrev    pgtype.Text
	UtcOffset sql.NullInt64
	IsDst     sql.NullBool
}

type PgTransform struct {
	Trftype    pgtype.OID
	Trflang    pgtype.OID
	Trffromsql pgtype.Text
	Trftosql   pgtype.Text
}

type PgTrigger struct {
	Tgrelid        pgtype.OID
	Tgname         string
	Tgfoid         pgtype.OID
	Tgtype         int16
	Tgenabled      pgtype.QChar
	Tgisinternal   bool
	Tgconstrrelid  pgtype.OID
	Tgconstrindid  pgtype.OID
	Tgconstraint   pgtype.OID
	Tgdeferrable   bool
	Tginitdeferred bool
	Tgnargs        int16
	Tgattr         []int16
	Tgargs         pgtype.Bytea
	Tgqual         interface{}
	Tgoldtable     pgtype.Name
	Tgnewtable     pgtype.Name
}

type PgTsConfig struct {
	Cfgname      string
	Cfgnamespace pgtype.OID
	Cfgowner     pgtype.OID
	Cfgparser    pgtype.OID
}

type PgTsConfigMap struct {
	Mapcfg       pgtype.OID
	Maptokentype int32
	Mapseqno     int32
	Mapdict      pgtype.OID
}

type PgTsDict struct {
	Dictname       string
	Dictnamespace  pgtype.OID
	Dictowner      pgtype.OID
	Dicttemplate   pgtype.OID
	Dictinitoption pgtype.Text
}

type PgTsParser struct {
	Prsname      string
	Prsnamespace pgtype.OID
	Prsstart     pgtype.Text
	Prstoken     pgtype.Text
	Prsend       pgtype.Text
	Prsheadline  pgtype.Text
	Prslextype   pgtype.Text
}

type PgTsTemplate struct {
	Tmplname      string
	Tmplnamespace pgtype.OID
	Tmplinit      pgtype.Text
	Tmpllexize    pgtype.Text
}

type PgType struct {
	Typname        string
	Typnamespace   pgtype.OID
	Typowner       pgtype.OID
	Typlen         int16
	Typbyval       bool
	Typtype        pgtype.QChar
	Typcategory    pgtype.QChar
	Typispreferred bool
	Typisdefined   bool
	Typdelim       pgtype.QChar
	Typrelid       pgtype.OID
	Typelem        pgtype.OID
	Typarray       pgtype.OID
	Typinput       pgtype.Text
	Typoutput      pgtype.Text
	Typreceive     pgtype.Text
	Typsend        pgtype.Text
	Typmodin       pgtype.Text
	Typmodout      pgtype.Text
	Typanalyze     pgtype.Text
	Typalign       pgtype.QChar
	Typstorage     pgtype.QChar
	Typnotnull     bool
	Typbasetype    pgtype.OID
	Typtypmod      int32
	Typndims       int32
	Typcollation   pgtype.OID
	Typdefaultbin  interface{}
	Typdefault     pgtype.Text
	Typacl         []pgtype.ACLItem
}

type PgUser struct {
	Usename      pgtype.Name
	Usesysid     pgtype.OIDValue
	Usecreatedb  sql.NullBool
	Usesuper     sql.NullBool
	Userepl      sql.NullBool
	Usebypassrls sql.NullBool
	Passwd       pgtype.Text
	Valuntil     interface{}
	Useconfig    []pgtype.Text
}

type PgUserMapping struct {
	Umuser    pgtype.OID
	Umserver  pgtype.OID
	Umoptions []pgtype.Text
}

type PgUserMappings struct {
	Umid      pgtype.OIDValue
	Srvid     pgtype.OIDValue
	Srvname   pgtype.Name
	Umuser    pgtype.OIDValue
	Usename   pgtype.Name
	Umoptions []pgtype.Text
}

type PgViews struct {
	Schemaname pgtype.Name
	Viewname   pgtype.Name
	Viewowner  pgtype.Name
	Definition pgtype.Text
}
