#!/bin/sh
set -e

echo ========================================
go version
echo ========================================
printenv | sort
echo ========================================
mkdir -p dist
go test -race -coverpkg ./... -coverprofile=dist/coverage.txt -tags "${PGUTIL_TEST_TAGS:-'integration'}" ./...
echo ========================================
echo go vet...
go vet  ./...
echo ========================================
echo golangci-lint...
golangci-lint run
