
//line foreign_key_parser.rl:1
package ddl

// Code generated by go generate; DO NOT EDIT.

import (
	"bytes"
)


//line foreign_key_parser.go:13
const foreign_key_start int = 1
const foreign_key_first_final int = 186
const foreign_key_error int = 0

const foreign_key_en_main int = 1


//line foreign_key_parser.rl:12


func ParseForeignKey(data string) (*ForeignKey, error) {
	fk := &ForeignKey{}

	buffer := &bytes.Buffer{}
	cs, eof := 0, len(data);
	p, pe := 0, eof;
	
//line foreign_key_parser.go:31
	{
	cs = foreign_key_start
	}

//line foreign_key_parser.go:36
	{
	if p == pe {
		goto _test_eof
	}
	switch cs {
	case 1:
		goto st_case_1
	case 0:
		goto st_case_0
	case 2:
		goto st_case_2
	case 3:
		goto st_case_3
	case 4:
		goto st_case_4
	case 5:
		goto st_case_5
	case 6:
		goto st_case_6
	case 7:
		goto st_case_7
	case 8:
		goto st_case_8
	case 9:
		goto st_case_9
	case 10:
		goto st_case_10
	case 11:
		goto st_case_11
	case 12:
		goto st_case_12
	case 13:
		goto st_case_13
	case 14:
		goto st_case_14
	case 15:
		goto st_case_15
	case 16:
		goto st_case_16
	case 17:
		goto st_case_17
	case 18:
		goto st_case_18
	case 19:
		goto st_case_19
	case 20:
		goto st_case_20
	case 21:
		goto st_case_21
	case 22:
		goto st_case_22
	case 23:
		goto st_case_23
	case 24:
		goto st_case_24
	case 25:
		goto st_case_25
	case 26:
		goto st_case_26
	case 27:
		goto st_case_27
	case 28:
		goto st_case_28
	case 29:
		goto st_case_29
	case 30:
		goto st_case_30
	case 31:
		goto st_case_31
	case 32:
		goto st_case_32
	case 33:
		goto st_case_33
	case 186:
		goto st_case_186
	case 187:
		goto st_case_187
	case 34:
		goto st_case_34
	case 35:
		goto st_case_35
	case 36:
		goto st_case_36
	case 37:
		goto st_case_37
	case 38:
		goto st_case_38
	case 39:
		goto st_case_39
	case 40:
		goto st_case_40
	case 41:
		goto st_case_41
	case 42:
		goto st_case_42
	case 43:
		goto st_case_43
	case 188:
		goto st_case_188
	case 44:
		goto st_case_44
	case 45:
		goto st_case_45
	case 46:
		goto st_case_46
	case 47:
		goto st_case_47
	case 48:
		goto st_case_48
	case 49:
		goto st_case_49
	case 50:
		goto st_case_50
	case 51:
		goto st_case_51
	case 52:
		goto st_case_52
	case 53:
		goto st_case_53
	case 54:
		goto st_case_54
	case 55:
		goto st_case_55
	case 56:
		goto st_case_56
	case 57:
		goto st_case_57
	case 58:
		goto st_case_58
	case 59:
		goto st_case_59
	case 60:
		goto st_case_60
	case 189:
		goto st_case_189
	case 61:
		goto st_case_61
	case 62:
		goto st_case_62
	case 63:
		goto st_case_63
	case 64:
		goto st_case_64
	case 65:
		goto st_case_65
	case 66:
		goto st_case_66
	case 67:
		goto st_case_67
	case 68:
		goto st_case_68
	case 69:
		goto st_case_69
	case 70:
		goto st_case_70
	case 71:
		goto st_case_71
	case 72:
		goto st_case_72
	case 73:
		goto st_case_73
	case 74:
		goto st_case_74
	case 75:
		goto st_case_75
	case 76:
		goto st_case_76
	case 77:
		goto st_case_77
	case 190:
		goto st_case_190
	case 191:
		goto st_case_191
	case 78:
		goto st_case_78
	case 79:
		goto st_case_79
	case 80:
		goto st_case_80
	case 81:
		goto st_case_81
	case 82:
		goto st_case_82
	case 83:
		goto st_case_83
	case 84:
		goto st_case_84
	case 85:
		goto st_case_85
	case 86:
		goto st_case_86
	case 87:
		goto st_case_87
	case 88:
		goto st_case_88
	case 89:
		goto st_case_89
	case 90:
		goto st_case_90
	case 91:
		goto st_case_91
	case 92:
		goto st_case_92
	case 93:
		goto st_case_93
	case 94:
		goto st_case_94
	case 95:
		goto st_case_95
	case 96:
		goto st_case_96
	case 97:
		goto st_case_97
	case 98:
		goto st_case_98
	case 99:
		goto st_case_99
	case 100:
		goto st_case_100
	case 101:
		goto st_case_101
	case 102:
		goto st_case_102
	case 103:
		goto st_case_103
	case 104:
		goto st_case_104
	case 105:
		goto st_case_105
	case 192:
		goto st_case_192
	case 193:
		goto st_case_193
	case 106:
		goto st_case_106
	case 107:
		goto st_case_107
	case 108:
		goto st_case_108
	case 109:
		goto st_case_109
	case 110:
		goto st_case_110
	case 111:
		goto st_case_111
	case 112:
		goto st_case_112
	case 113:
		goto st_case_113
	case 114:
		goto st_case_114
	case 115:
		goto st_case_115
	case 116:
		goto st_case_116
	case 117:
		goto st_case_117
	case 118:
		goto st_case_118
	case 119:
		goto st_case_119
	case 120:
		goto st_case_120
	case 121:
		goto st_case_121
	case 194:
		goto st_case_194
	case 195:
		goto st_case_195
	case 122:
		goto st_case_122
	case 123:
		goto st_case_123
	case 124:
		goto st_case_124
	case 125:
		goto st_case_125
	case 126:
		goto st_case_126
	case 127:
		goto st_case_127
	case 128:
		goto st_case_128
	case 129:
		goto st_case_129
	case 130:
		goto st_case_130
	case 131:
		goto st_case_131
	case 132:
		goto st_case_132
	case 133:
		goto st_case_133
	case 134:
		goto st_case_134
	case 135:
		goto st_case_135
	case 136:
		goto st_case_136
	case 137:
		goto st_case_137
	case 138:
		goto st_case_138
	case 139:
		goto st_case_139
	case 140:
		goto st_case_140
	case 141:
		goto st_case_141
	case 142:
		goto st_case_142
	case 143:
		goto st_case_143
	case 144:
		goto st_case_144
	case 145:
		goto st_case_145
	case 146:
		goto st_case_146
	case 147:
		goto st_case_147
	case 148:
		goto st_case_148
	case 149:
		goto st_case_149
	case 150:
		goto st_case_150
	case 151:
		goto st_case_151
	case 152:
		goto st_case_152
	case 153:
		goto st_case_153
	case 154:
		goto st_case_154
	case 155:
		goto st_case_155
	case 156:
		goto st_case_156
	case 157:
		goto st_case_157
	case 158:
		goto st_case_158
	case 159:
		goto st_case_159
	case 160:
		goto st_case_160
	case 161:
		goto st_case_161
	case 162:
		goto st_case_162
	case 163:
		goto st_case_163
	case 164:
		goto st_case_164
	case 165:
		goto st_case_165
	case 166:
		goto st_case_166
	case 167:
		goto st_case_167
	case 168:
		goto st_case_168
	case 169:
		goto st_case_169
	case 170:
		goto st_case_170
	case 171:
		goto st_case_171
	case 172:
		goto st_case_172
	case 173:
		goto st_case_173
	case 174:
		goto st_case_174
	case 175:
		goto st_case_175
	case 176:
		goto st_case_176
	case 177:
		goto st_case_177
	case 178:
		goto st_case_178
	case 179:
		goto st_case_179
	case 180:
		goto st_case_180
	case 181:
		goto st_case_181
	case 182:
		goto st_case_182
	case 183:
		goto st_case_183
	case 184:
		goto st_case_184
	case 185:
		goto st_case_185
	}
	goto st_out
	st1:
		if p++; p == pe {
			goto _test_eof1
		}
	st_case_1:
		switch data[p] {
		case 32:
			goto st1
		case 70:
			goto st2
		case 102:
			goto st2
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st1
		}
		goto st0
st_case_0:
	st0:
		cs = 0
		goto _out
	st2:
		if p++; p == pe {
			goto _test_eof2
		}
	st_case_2:
		switch data[p] {
		case 79:
			goto st3
		case 111:
			goto st3
		}
		goto st0
	st3:
		if p++; p == pe {
			goto _test_eof3
		}
	st_case_3:
		switch data[p] {
		case 82:
			goto st4
		case 114:
			goto st4
		}
		goto st0
	st4:
		if p++; p == pe {
			goto _test_eof4
		}
	st_case_4:
		switch data[p] {
		case 69:
			goto st5
		case 101:
			goto st5
		}
		goto st0
	st5:
		if p++; p == pe {
			goto _test_eof5
		}
	st_case_5:
		switch data[p] {
		case 73:
			goto st6
		case 105:
			goto st6
		}
		goto st0
	st6:
		if p++; p == pe {
			goto _test_eof6
		}
	st_case_6:
		switch data[p] {
		case 71:
			goto st7
		case 103:
			goto st7
		}
		goto st0
	st7:
		if p++; p == pe {
			goto _test_eof7
		}
	st_case_7:
		switch data[p] {
		case 78:
			goto st8
		case 110:
			goto st8
		}
		goto st0
	st8:
		if p++; p == pe {
			goto _test_eof8
		}
	st_case_8:
		if data[p] == 32 {
			goto st9
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st9
		}
		goto st0
	st9:
		if p++; p == pe {
			goto _test_eof9
		}
	st_case_9:
		switch data[p] {
		case 32:
			goto st9
		case 75:
			goto st10
		case 107:
			goto st10
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st9
		}
		goto st0
	st10:
		if p++; p == pe {
			goto _test_eof10
		}
	st_case_10:
		switch data[p] {
		case 69:
			goto st11
		case 101:
			goto st11
		}
		goto st0
	st11:
		if p++; p == pe {
			goto _test_eof11
		}
	st_case_11:
		switch data[p] {
		case 89:
			goto st12
		case 121:
			goto st12
		}
		goto st0
	st12:
		if p++; p == pe {
			goto _test_eof12
		}
	st_case_12:
		if data[p] == 32 {
			goto st13
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st13
		}
		goto st0
	st13:
		if p++; p == pe {
			goto _test_eof13
		}
	st_case_13:
		switch data[p] {
		case 32:
			goto st13
		case 40:
			goto st14
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st13
		}
		goto st0
tr18:
//line foreign_key_parser.rl:26

		fk.addColumn(buffer.String())
		buffer.Reset()
	
	goto st14
	st14:
		if p++; p == pe {
			goto _test_eof14
		}
	st_case_14:
//line foreign_key_parser.go:621
		if data[p] == 32 {
			goto st14
		}
		switch {
		case data[p] < 65:
			if 9 <= data[p] && data[p] <= 13 {
				goto st14
			}
		case data[p] > 90:
			if 97 <= data[p] && data[p] <= 122 {
				goto tr15
			}
		default:
			goto tr15
		}
		goto st0
tr15:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st15
	st15:
		if p++; p == pe {
			goto _test_eof15
		}
	st_case_15:
//line foreign_key_parser.go:649
		switch data[p] {
		case 32:
			goto tr16
		case 41:
			goto tr17
		case 44:
			goto tr18
		case 95:
			goto tr15
		}
		switch {
		case data[p] < 48:
			if 9 <= data[p] && data[p] <= 13 {
				goto tr16
			}
		case data[p] > 57:
			switch {
			case data[p] > 90:
				if 97 <= data[p] && data[p] <= 122 {
					goto tr15
				}
			case data[p] >= 65:
				goto tr15
			}
		default:
			goto tr15
		}
		goto st0
tr16:
//line foreign_key_parser.rl:26

		fk.addColumn(buffer.String())
		buffer.Reset()
	
	goto st16
	st16:
		if p++; p == pe {
			goto _test_eof16
		}
	st_case_16:
//line foreign_key_parser.go:690
		switch data[p] {
		case 32:
			goto st16
		case 41:
			goto st17
		case 44:
			goto st14
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st16
		}
		goto st0
tr17:
//line foreign_key_parser.rl:26

		fk.addColumn(buffer.String())
		buffer.Reset()
	
	goto st17
	st17:
		if p++; p == pe {
			goto _test_eof17
		}
	st_case_17:
//line foreign_key_parser.go:715
		if data[p] == 32 {
			goto st18
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st18
		}
		goto st0
	st18:
		if p++; p == pe {
			goto _test_eof18
		}
	st_case_18:
		switch data[p] {
		case 32:
			goto st18
		case 82:
			goto st19
		case 114:
			goto st19
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st18
		}
		goto st0
	st19:
		if p++; p == pe {
			goto _test_eof19
		}
	st_case_19:
		switch data[p] {
		case 69:
			goto st20
		case 101:
			goto st20
		}
		goto st0
	st20:
		if p++; p == pe {
			goto _test_eof20
		}
	st_case_20:
		switch data[p] {
		case 70:
			goto st21
		case 102:
			goto st21
		}
		goto st0
	st21:
		if p++; p == pe {
			goto _test_eof21
		}
	st_case_21:
		switch data[p] {
		case 69:
			goto st22
		case 101:
			goto st22
		}
		goto st0
	st22:
		if p++; p == pe {
			goto _test_eof22
		}
	st_case_22:
		switch data[p] {
		case 82:
			goto st23
		case 114:
			goto st23
		}
		goto st0
	st23:
		if p++; p == pe {
			goto _test_eof23
		}
	st_case_23:
		switch data[p] {
		case 69:
			goto st24
		case 101:
			goto st24
		}
		goto st0
	st24:
		if p++; p == pe {
			goto _test_eof24
		}
	st_case_24:
		switch data[p] {
		case 78:
			goto st25
		case 110:
			goto st25
		}
		goto st0
	st25:
		if p++; p == pe {
			goto _test_eof25
		}
	st_case_25:
		switch data[p] {
		case 67:
			goto st26
		case 99:
			goto st26
		}
		goto st0
	st26:
		if p++; p == pe {
			goto _test_eof26
		}
	st_case_26:
		switch data[p] {
		case 69:
			goto st27
		case 101:
			goto st27
		}
		goto st0
	st27:
		if p++; p == pe {
			goto _test_eof27
		}
	st_case_27:
		switch data[p] {
		case 83:
			goto st28
		case 115:
			goto st28
		}
		goto st0
	st28:
		if p++; p == pe {
			goto _test_eof28
		}
	st_case_28:
		if data[p] == 32 {
			goto st29
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st29
		}
		goto st0
	st29:
		if p++; p == pe {
			goto _test_eof29
		}
	st_case_29:
		if data[p] == 32 {
			goto st29
		}
		switch {
		case data[p] < 65:
			if 9 <= data[p] && data[p] <= 13 {
				goto st29
			}
		case data[p] > 90:
			if 97 <= data[p] && data[p] <= 122 {
				goto tr33
			}
		default:
			goto tr33
		}
		goto st0
tr33:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st30
	st30:
		if p++; p == pe {
			goto _test_eof30
		}
	st_case_30:
//line foreign_key_parser.go:892
		switch data[p] {
		case 40:
			goto tr34
		case 95:
			goto tr33
		}
		switch {
		case data[p] < 65:
			if 48 <= data[p] && data[p] <= 57 {
				goto tr33
			}
		case data[p] > 90:
			if 97 <= data[p] && data[p] <= 122 {
				goto tr33
			}
		default:
			goto tr33
		}
		goto st0
tr34:
//line foreign_key_parser.rl:46

		fk.setTable(buffer.String())
		buffer.Reset()
	
	goto st31
tr39:
//line foreign_key_parser.rl:30

		fk.addReferenced(buffer.String())
		buffer.Reset()
	
	goto st31
	st31:
		if p++; p == pe {
			goto _test_eof31
		}
	st_case_31:
//line foreign_key_parser.go:931
		if data[p] == 32 {
			goto st31
		}
		switch {
		case data[p] < 65:
			if 9 <= data[p] && data[p] <= 13 {
				goto st31
			}
		case data[p] > 90:
			if 97 <= data[p] && data[p] <= 122 {
				goto tr36
			}
		default:
			goto tr36
		}
		goto st0
tr36:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st32
	st32:
		if p++; p == pe {
			goto _test_eof32
		}
	st_case_32:
//line foreign_key_parser.go:959
		switch data[p] {
		case 32:
			goto tr37
		case 41:
			goto tr38
		case 44:
			goto tr39
		case 95:
			goto tr36
		}
		switch {
		case data[p] < 48:
			if 9 <= data[p] && data[p] <= 13 {
				goto tr37
			}
		case data[p] > 57:
			switch {
			case data[p] > 90:
				if 97 <= data[p] && data[p] <= 122 {
					goto tr36
				}
			case data[p] >= 65:
				goto tr36
			}
		default:
			goto tr36
		}
		goto st0
tr37:
//line foreign_key_parser.rl:30

		fk.addReferenced(buffer.String())
		buffer.Reset()
	
	goto st33
	st33:
		if p++; p == pe {
			goto _test_eof33
		}
	st_case_33:
//line foreign_key_parser.go:1000
		switch data[p] {
		case 32:
			goto st33
		case 41:
			goto st186
		case 44:
			goto st31
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st33
		}
		goto st0
tr38:
//line foreign_key_parser.rl:30

		fk.addReferenced(buffer.String())
		buffer.Reset()
	
	goto st186
	st186:
		if p++; p == pe {
			goto _test_eof186
		}
	st_case_186:
//line foreign_key_parser.go:1025
		if data[p] == 32 {
			goto st187
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st187
		}
		goto st0
	st187:
		if p++; p == pe {
			goto _test_eof187
		}
	st_case_187:
		switch data[p] {
		case 32:
			goto st187
		case 68:
			goto st34
		case 73:
			goto st44
		case 77:
			goto st69
		case 78:
			goto st78
		case 79:
			goto st90
		case 100:
			goto st34
		case 105:
			goto st44
		case 109:
			goto st69
		case 110:
			goto st78
		case 111:
			goto st90
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st187
		}
		goto st0
	st34:
		if p++; p == pe {
			goto _test_eof34
		}
	st_case_34:
		switch data[p] {
		case 69:
			goto st35
		case 101:
			goto st35
		}
		goto st0
	st35:
		if p++; p == pe {
			goto _test_eof35
		}
	st_case_35:
		switch data[p] {
		case 70:
			goto st36
		case 102:
			goto st36
		}
		goto st0
	st36:
		if p++; p == pe {
			goto _test_eof36
		}
	st_case_36:
		switch data[p] {
		case 69:
			goto st37
		case 101:
			goto st37
		}
		goto st0
	st37:
		if p++; p == pe {
			goto _test_eof37
		}
	st_case_37:
		switch data[p] {
		case 82:
			goto st38
		case 114:
			goto st38
		}
		goto st0
	st38:
		if p++; p == pe {
			goto _test_eof38
		}
	st_case_38:
		switch data[p] {
		case 82:
			goto st39
		case 114:
			goto st39
		}
		goto st0
	st39:
		if p++; p == pe {
			goto _test_eof39
		}
	st_case_39:
		switch data[p] {
		case 65:
			goto st40
		case 97:
			goto st40
		}
		goto st0
	st40:
		if p++; p == pe {
			goto _test_eof40
		}
	st_case_40:
		switch data[p] {
		case 66:
			goto st41
		case 98:
			goto st41
		}
		goto st0
	st41:
		if p++; p == pe {
			goto _test_eof41
		}
	st_case_41:
		switch data[p] {
		case 76:
			goto st42
		case 108:
			goto st42
		}
		goto st0
	st42:
		if p++; p == pe {
			goto _test_eof42
		}
	st_case_42:
		switch data[p] {
		case 69:
			goto st43
		case 101:
			goto st43
		}
		goto st0
	st43:
		if p++; p == pe {
			goto _test_eof43
		}
	st_case_43:
		if data[p] == 32 {
			goto tr51
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto tr51
		}
		goto st0
tr51:
//line foreign_key_parser.rl:51
 fk.Deferrable = true 
	goto st188
	st188:
		if p++; p == pe {
			goto _test_eof188
		}
	st_case_188:
//line foreign_key_parser.go:1195
		switch data[p] {
		case 32:
			goto tr51
		case 73:
			goto st44
		case 105:
			goto st44
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto tr51
		}
		goto st0
	st44:
		if p++; p == pe {
			goto _test_eof44
		}
	st_case_44:
		switch data[p] {
		case 78:
			goto st45
		case 110:
			goto st45
		}
		goto st0
	st45:
		if p++; p == pe {
			goto _test_eof45
		}
	st_case_45:
		switch data[p] {
		case 73:
			goto st46
		case 105:
			goto st46
		}
		goto st0
	st46:
		if p++; p == pe {
			goto _test_eof46
		}
	st_case_46:
		switch data[p] {
		case 84:
			goto st47
		case 116:
			goto st47
		}
		goto st0
	st47:
		if p++; p == pe {
			goto _test_eof47
		}
	st_case_47:
		switch data[p] {
		case 73:
			goto st48
		case 105:
			goto st48
		}
		goto st0
	st48:
		if p++; p == pe {
			goto _test_eof48
		}
	st_case_48:
		switch data[p] {
		case 65:
			goto st49
		case 97:
			goto st49
		}
		goto st0
	st49:
		if p++; p == pe {
			goto _test_eof49
		}
	st_case_49:
		switch data[p] {
		case 76:
			goto st50
		case 108:
			goto st50
		}
		goto st0
	st50:
		if p++; p == pe {
			goto _test_eof50
		}
	st_case_50:
		switch data[p] {
		case 76:
			goto st51
		case 108:
			goto st51
		}
		goto st0
	st51:
		if p++; p == pe {
			goto _test_eof51
		}
	st_case_51:
		switch data[p] {
		case 89:
			goto st52
		case 121:
			goto st52
		}
		goto st0
	st52:
		if p++; p == pe {
			goto _test_eof52
		}
	st_case_52:
		if data[p] == 32 {
			goto st53
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st53
		}
		goto st0
	st53:
		if p++; p == pe {
			goto _test_eof53
		}
	st_case_53:
		switch data[p] {
		case 32:
			goto st53
		case 68:
			goto st54
		case 73:
			goto st61
		case 100:
			goto st54
		case 105:
			goto st61
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st53
		}
		goto st0
	st54:
		if p++; p == pe {
			goto _test_eof54
		}
	st_case_54:
		switch data[p] {
		case 69:
			goto st55
		case 101:
			goto st55
		}
		goto st0
	st55:
		if p++; p == pe {
			goto _test_eof55
		}
	st_case_55:
		switch data[p] {
		case 70:
			goto st56
		case 102:
			goto st56
		}
		goto st0
	st56:
		if p++; p == pe {
			goto _test_eof56
		}
	st_case_56:
		switch data[p] {
		case 69:
			goto st57
		case 101:
			goto st57
		}
		goto st0
	st57:
		if p++; p == pe {
			goto _test_eof57
		}
	st_case_57:
		switch data[p] {
		case 82:
			goto st58
		case 114:
			goto st58
		}
		goto st0
	st58:
		if p++; p == pe {
			goto _test_eof58
		}
	st_case_58:
		switch data[p] {
		case 82:
			goto st59
		case 114:
			goto st59
		}
		goto st0
	st59:
		if p++; p == pe {
			goto _test_eof59
		}
	st_case_59:
		switch data[p] {
		case 69:
			goto st60
		case 101:
			goto st60
		}
		goto st0
	st60:
		if p++; p == pe {
			goto _test_eof60
		}
	st_case_60:
		switch data[p] {
		case 68:
			goto tr69
		case 100:
			goto tr69
		}
		goto st0
tr69:
//line foreign_key_parser.rl:52
 fk.InitiallyDeferred = true 
	goto st189
	st189:
		if p++; p == pe {
			goto _test_eof189
		}
	st_case_189:
//line foreign_key_parser.go:1430
		if data[p] == 32 {
			goto st189
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st189
		}
		goto st0
	st61:
		if p++; p == pe {
			goto _test_eof61
		}
	st_case_61:
		switch data[p] {
		case 77:
			goto st62
		case 109:
			goto st62
		}
		goto st0
	st62:
		if p++; p == pe {
			goto _test_eof62
		}
	st_case_62:
		switch data[p] {
		case 77:
			goto st63
		case 109:
			goto st63
		}
		goto st0
	st63:
		if p++; p == pe {
			goto _test_eof63
		}
	st_case_63:
		switch data[p] {
		case 69:
			goto st64
		case 101:
			goto st64
		}
		goto st0
	st64:
		if p++; p == pe {
			goto _test_eof64
		}
	st_case_64:
		switch data[p] {
		case 68:
			goto st65
		case 100:
			goto st65
		}
		goto st0
	st65:
		if p++; p == pe {
			goto _test_eof65
		}
	st_case_65:
		switch data[p] {
		case 73:
			goto st66
		case 105:
			goto st66
		}
		goto st0
	st66:
		if p++; p == pe {
			goto _test_eof66
		}
	st_case_66:
		switch data[p] {
		case 65:
			goto st67
		case 97:
			goto st67
		}
		goto st0
	st67:
		if p++; p == pe {
			goto _test_eof67
		}
	st_case_67:
		switch data[p] {
		case 84:
			goto st68
		case 116:
			goto st68
		}
		goto st0
	st68:
		if p++; p == pe {
			goto _test_eof68
		}
	st_case_68:
		switch data[p] {
		case 69:
			goto st189
		case 101:
			goto st189
		}
		goto st0
	st69:
		if p++; p == pe {
			goto _test_eof69
		}
	st_case_69:
		switch data[p] {
		case 65:
			goto st70
		case 97:
			goto st70
		}
		goto st0
	st70:
		if p++; p == pe {
			goto _test_eof70
		}
	st_case_70:
		switch data[p] {
		case 84:
			goto st71
		case 116:
			goto st71
		}
		goto st0
	st71:
		if p++; p == pe {
			goto _test_eof71
		}
	st_case_71:
		switch data[p] {
		case 67:
			goto st72
		case 99:
			goto st72
		}
		goto st0
	st72:
		if p++; p == pe {
			goto _test_eof72
		}
	st_case_72:
		switch data[p] {
		case 72:
			goto st73
		case 104:
			goto st73
		}
		goto st0
	st73:
		if p++; p == pe {
			goto _test_eof73
		}
	st_case_73:
		if data[p] == 32 {
			goto st74
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st74
		}
		goto st0
	st74:
		if p++; p == pe {
			goto _test_eof74
		}
	st_case_74:
		switch data[p] {
		case 32:
			goto st74
		case 70:
			goto tr83
		case 80:
			goto tr84
		case 83:
			goto tr85
		case 102:
			goto tr83
		case 112:
			goto tr84
		case 115:
			goto tr85
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st74
		}
		goto st0
tr83:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st75
	st75:
		if p++; p == pe {
			goto _test_eof75
		}
	st_case_75:
//line foreign_key_parser.go:1630
		switch data[p] {
		case 85:
			goto tr86
		case 117:
			goto tr86
		}
		goto st0
tr86:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st76
	st76:
		if p++; p == pe {
			goto _test_eof76
		}
	st_case_76:
//line foreign_key_parser.go:1649
		switch data[p] {
		case 76:
			goto tr87
		case 108:
			goto tr87
		}
		goto st0
tr87:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st77
	st77:
		if p++; p == pe {
			goto _test_eof77
		}
	st_case_77:
//line foreign_key_parser.go:1668
		switch data[p] {
		case 76:
			goto tr88
		case 108:
			goto tr88
		}
		goto st0
tr88:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st190
	st190:
		if p++; p == pe {
			goto _test_eof190
		}
	st_case_190:
//line foreign_key_parser.go:1687
		if data[p] == 32 {
			goto tr200
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto tr200
		}
		goto st0
tr200:
//line foreign_key_parser.rl:34

		fk.setMatch(buffer.String())
		buffer.Reset()
	
	goto st191
	st191:
		if p++; p == pe {
			goto _test_eof191
		}
	st_case_191:
//line foreign_key_parser.go:1707
		switch data[p] {
		case 32:
			goto st191
		case 68:
			goto st34
		case 73:
			goto st44
		case 78:
			goto st78
		case 79:
			goto st90
		case 100:
			goto st34
		case 105:
			goto st44
		case 110:
			goto st78
		case 111:
			goto st90
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st191
		}
		goto st0
	st78:
		if p++; p == pe {
			goto _test_eof78
		}
	st_case_78:
		switch data[p] {
		case 79:
			goto st79
		case 111:
			goto st79
		}
		goto st0
	st79:
		if p++; p == pe {
			goto _test_eof79
		}
	st_case_79:
		switch data[p] {
		case 84:
			goto st80
		case 116:
			goto st80
		}
		goto st0
	st80:
		if p++; p == pe {
			goto _test_eof80
		}
	st_case_80:
		if data[p] == 32 {
			goto st81
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st81
		}
		goto st0
	st81:
		if p++; p == pe {
			goto _test_eof81
		}
	st_case_81:
		switch data[p] {
		case 32:
			goto st81
		case 68:
			goto st82
		case 100:
			goto st82
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st81
		}
		goto st0
	st82:
		if p++; p == pe {
			goto _test_eof82
		}
	st_case_82:
		switch data[p] {
		case 69:
			goto st83
		case 101:
			goto st83
		}
		goto st0
	st83:
		if p++; p == pe {
			goto _test_eof83
		}
	st_case_83:
		switch data[p] {
		case 70:
			goto st84
		case 102:
			goto st84
		}
		goto st0
	st84:
		if p++; p == pe {
			goto _test_eof84
		}
	st_case_84:
		switch data[p] {
		case 69:
			goto st85
		case 101:
			goto st85
		}
		goto st0
	st85:
		if p++; p == pe {
			goto _test_eof85
		}
	st_case_85:
		switch data[p] {
		case 82:
			goto st86
		case 114:
			goto st86
		}
		goto st0
	st86:
		if p++; p == pe {
			goto _test_eof86
		}
	st_case_86:
		switch data[p] {
		case 82:
			goto st87
		case 114:
			goto st87
		}
		goto st0
	st87:
		if p++; p == pe {
			goto _test_eof87
		}
	st_case_87:
		switch data[p] {
		case 65:
			goto st88
		case 97:
			goto st88
		}
		goto st0
	st88:
		if p++; p == pe {
			goto _test_eof88
		}
	st_case_88:
		switch data[p] {
		case 66:
			goto st89
		case 98:
			goto st89
		}
		goto st0
	st89:
		if p++; p == pe {
			goto _test_eof89
		}
	st_case_89:
		switch data[p] {
		case 76:
			goto st68
		case 108:
			goto st68
		}
		goto st0
	st90:
		if p++; p == pe {
			goto _test_eof90
		}
	st_case_90:
		switch data[p] {
		case 78:
			goto st91
		case 110:
			goto st91
		}
		goto st0
	st91:
		if p++; p == pe {
			goto _test_eof91
		}
	st_case_91:
		if data[p] == 32 {
			goto st92
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st92
		}
		goto st0
	st92:
		if p++; p == pe {
			goto _test_eof92
		}
	st_case_92:
		switch data[p] {
		case 32:
			goto st92
		case 68:
			goto st93
		case 85:
			goto st109
		case 100:
			goto st93
		case 117:
			goto st109
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st92
		}
		goto st0
	st93:
		if p++; p == pe {
			goto _test_eof93
		}
	st_case_93:
		switch data[p] {
		case 69:
			goto st94
		case 101:
			goto st94
		}
		goto st0
	st94:
		if p++; p == pe {
			goto _test_eof94
		}
	st_case_94:
		switch data[p] {
		case 76:
			goto st95
		case 108:
			goto st95
		}
		goto st0
	st95:
		if p++; p == pe {
			goto _test_eof95
		}
	st_case_95:
		switch data[p] {
		case 69:
			goto st96
		case 101:
			goto st96
		}
		goto st0
	st96:
		if p++; p == pe {
			goto _test_eof96
		}
	st_case_96:
		switch data[p] {
		case 84:
			goto st97
		case 116:
			goto st97
		}
		goto st0
	st97:
		if p++; p == pe {
			goto _test_eof97
		}
	st_case_97:
		switch data[p] {
		case 69:
			goto st98
		case 101:
			goto st98
		}
		goto st0
	st98:
		if p++; p == pe {
			goto _test_eof98
		}
	st_case_98:
		if data[p] == 32 {
			goto st99
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st99
		}
		goto st0
	st99:
		if p++; p == pe {
			goto _test_eof99
		}
	st_case_99:
		switch data[p] {
		case 32:
			goto st99
		case 67:
			goto tr110
		case 78:
			goto tr111
		case 82:
			goto tr112
		case 83:
			goto tr113
		case 99:
			goto tr110
		case 110:
			goto tr111
		case 114:
			goto tr112
		case 115:
			goto tr113
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st99
		}
		goto st0
tr110:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st100
	st100:
		if p++; p == pe {
			goto _test_eof100
		}
	st_case_100:
//line foreign_key_parser.go:2038
		switch data[p] {
		case 65:
			goto tr114
		case 97:
			goto tr114
		}
		goto st0
tr114:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st101
	st101:
		if p++; p == pe {
			goto _test_eof101
		}
	st_case_101:
//line foreign_key_parser.go:2057
		switch data[p] {
		case 83:
			goto tr115
		case 115:
			goto tr115
		}
		goto st0
tr115:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st102
	st102:
		if p++; p == pe {
			goto _test_eof102
		}
	st_case_102:
//line foreign_key_parser.go:2076
		switch data[p] {
		case 67:
			goto tr116
		case 99:
			goto tr116
		}
		goto st0
tr116:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st103
	st103:
		if p++; p == pe {
			goto _test_eof103
		}
	st_case_103:
//line foreign_key_parser.go:2095
		switch data[p] {
		case 65:
			goto tr117
		case 97:
			goto tr117
		}
		goto st0
tr117:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st104
	st104:
		if p++; p == pe {
			goto _test_eof104
		}
	st_case_104:
//line foreign_key_parser.go:2114
		switch data[p] {
		case 68:
			goto tr118
		case 100:
			goto tr118
		}
		goto st0
tr118:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st105
	st105:
		if p++; p == pe {
			goto _test_eof105
		}
	st_case_105:
//line foreign_key_parser.go:2133
		switch data[p] {
		case 69:
			goto tr119
		case 101:
			goto tr119
		}
		goto st0
tr119:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st192
	st192:
		if p++; p == pe {
			goto _test_eof192
		}
	st_case_192:
//line foreign_key_parser.go:2152
		if data[p] == 32 {
			goto tr202
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto tr202
		}
		goto st0
tr202:
//line foreign_key_parser.rl:38

		fk.setOnDelete(buffer.String())
		buffer.Reset()
	
	goto st193
	st193:
		if p++; p == pe {
			goto _test_eof193
		}
	st_case_193:
//line foreign_key_parser.go:2172
		switch data[p] {
		case 32:
			goto st193
		case 68:
			goto st34
		case 73:
			goto st44
		case 78:
			goto st78
		case 79:
			goto st106
		case 100:
			goto st34
		case 105:
			goto st44
		case 110:
			goto st78
		case 111:
			goto st106
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st193
		}
		goto st0
	st106:
		if p++; p == pe {
			goto _test_eof106
		}
	st_case_106:
		switch data[p] {
		case 78:
			goto st107
		case 110:
			goto st107
		}
		goto st0
	st107:
		if p++; p == pe {
			goto _test_eof107
		}
	st_case_107:
		if data[p] == 32 {
			goto st108
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st108
		}
		goto st0
	st108:
		if p++; p == pe {
			goto _test_eof108
		}
	st_case_108:
		switch data[p] {
		case 32:
			goto st108
		case 85:
			goto st109
		case 117:
			goto st109
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st108
		}
		goto st0
	st109:
		if p++; p == pe {
			goto _test_eof109
		}
	st_case_109:
		switch data[p] {
		case 80:
			goto st110
		case 112:
			goto st110
		}
		goto st0
	st110:
		if p++; p == pe {
			goto _test_eof110
		}
	st_case_110:
		switch data[p] {
		case 68:
			goto st111
		case 100:
			goto st111
		}
		goto st0
	st111:
		if p++; p == pe {
			goto _test_eof111
		}
	st_case_111:
		switch data[p] {
		case 65:
			goto st112
		case 97:
			goto st112
		}
		goto st0
	st112:
		if p++; p == pe {
			goto _test_eof112
		}
	st_case_112:
		switch data[p] {
		case 84:
			goto st113
		case 116:
			goto st113
		}
		goto st0
	st113:
		if p++; p == pe {
			goto _test_eof113
		}
	st_case_113:
		switch data[p] {
		case 69:
			goto st114
		case 101:
			goto st114
		}
		goto st0
	st114:
		if p++; p == pe {
			goto _test_eof114
		}
	st_case_114:
		if data[p] == 32 {
			goto st115
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st115
		}
		goto st0
	st115:
		if p++; p == pe {
			goto _test_eof115
		}
	st_case_115:
		switch data[p] {
		case 32:
			goto st115
		case 67:
			goto tr128
		case 78:
			goto tr129
		case 82:
			goto tr130
		case 83:
			goto tr131
		case 99:
			goto tr128
		case 110:
			goto tr129
		case 114:
			goto tr130
		case 115:
			goto tr131
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st115
		}
		goto st0
tr128:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st116
	st116:
		if p++; p == pe {
			goto _test_eof116
		}
	st_case_116:
//line foreign_key_parser.go:2350
		switch data[p] {
		case 65:
			goto tr132
		case 97:
			goto tr132
		}
		goto st0
tr132:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st117
	st117:
		if p++; p == pe {
			goto _test_eof117
		}
	st_case_117:
//line foreign_key_parser.go:2369
		switch data[p] {
		case 83:
			goto tr133
		case 115:
			goto tr133
		}
		goto st0
tr133:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st118
	st118:
		if p++; p == pe {
			goto _test_eof118
		}
	st_case_118:
//line foreign_key_parser.go:2388
		switch data[p] {
		case 67:
			goto tr134
		case 99:
			goto tr134
		}
		goto st0
tr134:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st119
	st119:
		if p++; p == pe {
			goto _test_eof119
		}
	st_case_119:
//line foreign_key_parser.go:2407
		switch data[p] {
		case 65:
			goto tr135
		case 97:
			goto tr135
		}
		goto st0
tr135:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st120
	st120:
		if p++; p == pe {
			goto _test_eof120
		}
	st_case_120:
//line foreign_key_parser.go:2426
		switch data[p] {
		case 68:
			goto tr136
		case 100:
			goto tr136
		}
		goto st0
tr136:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st121
	st121:
		if p++; p == pe {
			goto _test_eof121
		}
	st_case_121:
//line foreign_key_parser.go:2445
		switch data[p] {
		case 69:
			goto tr137
		case 101:
			goto tr137
		}
		goto st0
tr137:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st194
	st194:
		if p++; p == pe {
			goto _test_eof194
		}
	st_case_194:
//line foreign_key_parser.go:2464
		if data[p] == 32 {
			goto tr205
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto tr205
		}
		goto st0
tr205:
//line foreign_key_parser.rl:42

		fk.setOnUpdate(buffer.String())
		buffer.Reset()
	
	goto st195
	st195:
		if p++; p == pe {
			goto _test_eof195
		}
	st_case_195:
//line foreign_key_parser.go:2484
		switch data[p] {
		case 32:
			goto st195
		case 68:
			goto st34
		case 73:
			goto st44
		case 78:
			goto st78
		case 100:
			goto st34
		case 105:
			goto st44
		case 110:
			goto st78
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto st195
		}
		goto st0
tr129:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st122
	st122:
		if p++; p == pe {
			goto _test_eof122
		}
	st_case_122:
//line foreign_key_parser.go:2516
		switch data[p] {
		case 79:
			goto tr138
		case 111:
			goto tr138
		}
		goto st0
tr138:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st123
	st123:
		if p++; p == pe {
			goto _test_eof123
		}
	st_case_123:
//line foreign_key_parser.go:2535
		if data[p] == 32 {
			goto tr139
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto tr139
		}
		goto st0
tr139:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st124
	st124:
		if p++; p == pe {
			goto _test_eof124
		}
	st_case_124:
//line foreign_key_parser.go:2554
		switch data[p] {
		case 32:
			goto tr139
		case 65:
			goto tr140
		case 97:
			goto tr140
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto tr139
		}
		goto st0
tr140:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st125
	st125:
		if p++; p == pe {
			goto _test_eof125
		}
	st_case_125:
//line foreign_key_parser.go:2578
		switch data[p] {
		case 67:
			goto tr141
		case 99:
			goto tr141
		}
		goto st0
tr141:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st126
	st126:
		if p++; p == pe {
			goto _test_eof126
		}
	st_case_126:
//line foreign_key_parser.go:2597
		switch data[p] {
		case 84:
			goto tr142
		case 116:
			goto tr142
		}
		goto st0
tr142:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st127
	st127:
		if p++; p == pe {
			goto _test_eof127
		}
	st_case_127:
//line foreign_key_parser.go:2616
		switch data[p] {
		case 73:
			goto tr143
		case 105:
			goto tr143
		}
		goto st0
tr143:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st128
	st128:
		if p++; p == pe {
			goto _test_eof128
		}
	st_case_128:
//line foreign_key_parser.go:2635
		switch data[p] {
		case 79:
			goto tr144
		case 111:
			goto tr144
		}
		goto st0
tr144:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st129
	st129:
		if p++; p == pe {
			goto _test_eof129
		}
	st_case_129:
//line foreign_key_parser.go:2654
		switch data[p] {
		case 78:
			goto tr137
		case 110:
			goto tr137
		}
		goto st0
tr130:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st130
	st130:
		if p++; p == pe {
			goto _test_eof130
		}
	st_case_130:
//line foreign_key_parser.go:2673
		switch data[p] {
		case 69:
			goto tr145
		case 101:
			goto tr145
		}
		goto st0
tr145:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st131
	st131:
		if p++; p == pe {
			goto _test_eof131
		}
	st_case_131:
//line foreign_key_parser.go:2692
		switch data[p] {
		case 83:
			goto tr146
		case 115:
			goto tr146
		}
		goto st0
tr146:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st132
	st132:
		if p++; p == pe {
			goto _test_eof132
		}
	st_case_132:
//line foreign_key_parser.go:2711
		switch data[p] {
		case 84:
			goto tr147
		case 116:
			goto tr147
		}
		goto st0
tr147:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st133
	st133:
		if p++; p == pe {
			goto _test_eof133
		}
	st_case_133:
//line foreign_key_parser.go:2730
		switch data[p] {
		case 82:
			goto tr148
		case 114:
			goto tr148
		}
		goto st0
tr148:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st134
	st134:
		if p++; p == pe {
			goto _test_eof134
		}
	st_case_134:
//line foreign_key_parser.go:2749
		switch data[p] {
		case 73:
			goto tr149
		case 105:
			goto tr149
		}
		goto st0
tr149:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st135
	st135:
		if p++; p == pe {
			goto _test_eof135
		}
	st_case_135:
//line foreign_key_parser.go:2768
		switch data[p] {
		case 67:
			goto tr150
		case 99:
			goto tr150
		}
		goto st0
tr150:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st136
	st136:
		if p++; p == pe {
			goto _test_eof136
		}
	st_case_136:
//line foreign_key_parser.go:2787
		switch data[p] {
		case 84:
			goto tr137
		case 116:
			goto tr137
		}
		goto st0
tr131:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st137
	st137:
		if p++; p == pe {
			goto _test_eof137
		}
	st_case_137:
//line foreign_key_parser.go:2806
		switch data[p] {
		case 69:
			goto tr151
		case 101:
			goto tr151
		}
		goto st0
tr151:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st138
	st138:
		if p++; p == pe {
			goto _test_eof138
		}
	st_case_138:
//line foreign_key_parser.go:2825
		switch data[p] {
		case 84:
			goto tr152
		case 116:
			goto tr152
		}
		goto st0
tr152:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st139
	st139:
		if p++; p == pe {
			goto _test_eof139
		}
	st_case_139:
//line foreign_key_parser.go:2844
		if data[p] == 32 {
			goto tr153
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto tr153
		}
		goto st0
tr153:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st140
	st140:
		if p++; p == pe {
			goto _test_eof140
		}
	st_case_140:
//line foreign_key_parser.go:2863
		switch data[p] {
		case 32:
			goto tr153
		case 68:
			goto tr154
		case 78:
			goto tr155
		case 100:
			goto tr154
		case 110:
			goto tr155
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto tr153
		}
		goto st0
tr154:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st141
	st141:
		if p++; p == pe {
			goto _test_eof141
		}
	st_case_141:
//line foreign_key_parser.go:2891
		switch data[p] {
		case 69:
			goto tr156
		case 101:
			goto tr156
		}
		goto st0
tr156:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st142
	st142:
		if p++; p == pe {
			goto _test_eof142
		}
	st_case_142:
//line foreign_key_parser.go:2910
		switch data[p] {
		case 70:
			goto tr157
		case 102:
			goto tr157
		}
		goto st0
tr157:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st143
	st143:
		if p++; p == pe {
			goto _test_eof143
		}
	st_case_143:
//line foreign_key_parser.go:2929
		switch data[p] {
		case 65:
			goto tr158
		case 97:
			goto tr158
		}
		goto st0
tr158:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st144
	st144:
		if p++; p == pe {
			goto _test_eof144
		}
	st_case_144:
//line foreign_key_parser.go:2948
		switch data[p] {
		case 85:
			goto tr159
		case 117:
			goto tr159
		}
		goto st0
tr159:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st145
	st145:
		if p++; p == pe {
			goto _test_eof145
		}
	st_case_145:
//line foreign_key_parser.go:2967
		switch data[p] {
		case 76:
			goto tr150
		case 108:
			goto tr150
		}
		goto st0
tr155:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st146
	st146:
		if p++; p == pe {
			goto _test_eof146
		}
	st_case_146:
//line foreign_key_parser.go:2986
		switch data[p] {
		case 85:
			goto tr160
		case 117:
			goto tr160
		}
		goto st0
tr160:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st147
	st147:
		if p++; p == pe {
			goto _test_eof147
		}
	st_case_147:
//line foreign_key_parser.go:3005
		switch data[p] {
		case 76:
			goto tr161
		case 108:
			goto tr161
		}
		goto st0
tr161:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st148
	st148:
		if p++; p == pe {
			goto _test_eof148
		}
	st_case_148:
//line foreign_key_parser.go:3024
		switch data[p] {
		case 76:
			goto tr137
		case 108:
			goto tr137
		}
		goto st0
tr111:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st149
	st149:
		if p++; p == pe {
			goto _test_eof149
		}
	st_case_149:
//line foreign_key_parser.go:3043
		switch data[p] {
		case 79:
			goto tr162
		case 111:
			goto tr162
		}
		goto st0
tr162:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st150
	st150:
		if p++; p == pe {
			goto _test_eof150
		}
	st_case_150:
//line foreign_key_parser.go:3062
		if data[p] == 32 {
			goto tr163
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto tr163
		}
		goto st0
tr163:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st151
	st151:
		if p++; p == pe {
			goto _test_eof151
		}
	st_case_151:
//line foreign_key_parser.go:3081
		switch data[p] {
		case 32:
			goto tr163
		case 65:
			goto tr164
		case 97:
			goto tr164
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto tr163
		}
		goto st0
tr164:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st152
	st152:
		if p++; p == pe {
			goto _test_eof152
		}
	st_case_152:
//line foreign_key_parser.go:3105
		switch data[p] {
		case 67:
			goto tr165
		case 99:
			goto tr165
		}
		goto st0
tr165:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st153
	st153:
		if p++; p == pe {
			goto _test_eof153
		}
	st_case_153:
//line foreign_key_parser.go:3124
		switch data[p] {
		case 84:
			goto tr166
		case 116:
			goto tr166
		}
		goto st0
tr166:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st154
	st154:
		if p++; p == pe {
			goto _test_eof154
		}
	st_case_154:
//line foreign_key_parser.go:3143
		switch data[p] {
		case 73:
			goto tr167
		case 105:
			goto tr167
		}
		goto st0
tr167:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st155
	st155:
		if p++; p == pe {
			goto _test_eof155
		}
	st_case_155:
//line foreign_key_parser.go:3162
		switch data[p] {
		case 79:
			goto tr168
		case 111:
			goto tr168
		}
		goto st0
tr168:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st156
	st156:
		if p++; p == pe {
			goto _test_eof156
		}
	st_case_156:
//line foreign_key_parser.go:3181
		switch data[p] {
		case 78:
			goto tr119
		case 110:
			goto tr119
		}
		goto st0
tr112:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st157
	st157:
		if p++; p == pe {
			goto _test_eof157
		}
	st_case_157:
//line foreign_key_parser.go:3200
		switch data[p] {
		case 69:
			goto tr169
		case 101:
			goto tr169
		}
		goto st0
tr169:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st158
	st158:
		if p++; p == pe {
			goto _test_eof158
		}
	st_case_158:
//line foreign_key_parser.go:3219
		switch data[p] {
		case 83:
			goto tr170
		case 115:
			goto tr170
		}
		goto st0
tr170:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st159
	st159:
		if p++; p == pe {
			goto _test_eof159
		}
	st_case_159:
//line foreign_key_parser.go:3238
		switch data[p] {
		case 84:
			goto tr171
		case 116:
			goto tr171
		}
		goto st0
tr171:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st160
	st160:
		if p++; p == pe {
			goto _test_eof160
		}
	st_case_160:
//line foreign_key_parser.go:3257
		switch data[p] {
		case 82:
			goto tr172
		case 114:
			goto tr172
		}
		goto st0
tr172:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st161
	st161:
		if p++; p == pe {
			goto _test_eof161
		}
	st_case_161:
//line foreign_key_parser.go:3276
		switch data[p] {
		case 73:
			goto tr173
		case 105:
			goto tr173
		}
		goto st0
tr173:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st162
	st162:
		if p++; p == pe {
			goto _test_eof162
		}
	st_case_162:
//line foreign_key_parser.go:3295
		switch data[p] {
		case 67:
			goto tr174
		case 99:
			goto tr174
		}
		goto st0
tr174:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st163
	st163:
		if p++; p == pe {
			goto _test_eof163
		}
	st_case_163:
//line foreign_key_parser.go:3314
		switch data[p] {
		case 84:
			goto tr119
		case 116:
			goto tr119
		}
		goto st0
tr113:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st164
	st164:
		if p++; p == pe {
			goto _test_eof164
		}
	st_case_164:
//line foreign_key_parser.go:3333
		switch data[p] {
		case 69:
			goto tr175
		case 101:
			goto tr175
		}
		goto st0
tr175:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st165
	st165:
		if p++; p == pe {
			goto _test_eof165
		}
	st_case_165:
//line foreign_key_parser.go:3352
		switch data[p] {
		case 84:
			goto tr176
		case 116:
			goto tr176
		}
		goto st0
tr176:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st166
	st166:
		if p++; p == pe {
			goto _test_eof166
		}
	st_case_166:
//line foreign_key_parser.go:3371
		if data[p] == 32 {
			goto tr177
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto tr177
		}
		goto st0
tr177:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st167
	st167:
		if p++; p == pe {
			goto _test_eof167
		}
	st_case_167:
//line foreign_key_parser.go:3390
		switch data[p] {
		case 32:
			goto tr177
		case 68:
			goto tr178
		case 78:
			goto tr179
		case 100:
			goto tr178
		case 110:
			goto tr179
		}
		if 9 <= data[p] && data[p] <= 13 {
			goto tr177
		}
		goto st0
tr178:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st168
	st168:
		if p++; p == pe {
			goto _test_eof168
		}
	st_case_168:
//line foreign_key_parser.go:3418
		switch data[p] {
		case 69:
			goto tr180
		case 101:
			goto tr180
		}
		goto st0
tr180:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st169
	st169:
		if p++; p == pe {
			goto _test_eof169
		}
	st_case_169:
//line foreign_key_parser.go:3437
		switch data[p] {
		case 70:
			goto tr181
		case 102:
			goto tr181
		}
		goto st0
tr181:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st170
	st170:
		if p++; p == pe {
			goto _test_eof170
		}
	st_case_170:
//line foreign_key_parser.go:3456
		switch data[p] {
		case 65:
			goto tr182
		case 97:
			goto tr182
		}
		goto st0
tr182:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st171
	st171:
		if p++; p == pe {
			goto _test_eof171
		}
	st_case_171:
//line foreign_key_parser.go:3475
		switch data[p] {
		case 85:
			goto tr183
		case 117:
			goto tr183
		}
		goto st0
tr183:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st172
	st172:
		if p++; p == pe {
			goto _test_eof172
		}
	st_case_172:
//line foreign_key_parser.go:3494
		switch data[p] {
		case 76:
			goto tr174
		case 108:
			goto tr174
		}
		goto st0
tr179:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st173
	st173:
		if p++; p == pe {
			goto _test_eof173
		}
	st_case_173:
//line foreign_key_parser.go:3513
		switch data[p] {
		case 85:
			goto tr184
		case 117:
			goto tr184
		}
		goto st0
tr184:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st174
	st174:
		if p++; p == pe {
			goto _test_eof174
		}
	st_case_174:
//line foreign_key_parser.go:3532
		switch data[p] {
		case 76:
			goto tr185
		case 108:
			goto tr185
		}
		goto st0
tr185:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st175
	st175:
		if p++; p == pe {
			goto _test_eof175
		}
	st_case_175:
//line foreign_key_parser.go:3551
		switch data[p] {
		case 76:
			goto tr119
		case 108:
			goto tr119
		}
		goto st0
tr84:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st176
	st176:
		if p++; p == pe {
			goto _test_eof176
		}
	st_case_176:
//line foreign_key_parser.go:3570
		switch data[p] {
		case 65:
			goto tr186
		case 97:
			goto tr186
		}
		goto st0
tr186:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st177
	st177:
		if p++; p == pe {
			goto _test_eof177
		}
	st_case_177:
//line foreign_key_parser.go:3589
		switch data[p] {
		case 82:
			goto tr187
		case 114:
			goto tr187
		}
		goto st0
tr187:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st178
	st178:
		if p++; p == pe {
			goto _test_eof178
		}
	st_case_178:
//line foreign_key_parser.go:3608
		switch data[p] {
		case 84:
			goto tr188
		case 116:
			goto tr188
		}
		goto st0
tr188:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st179
	st179:
		if p++; p == pe {
			goto _test_eof179
		}
	st_case_179:
//line foreign_key_parser.go:3627
		switch data[p] {
		case 73:
			goto tr189
		case 105:
			goto tr189
		}
		goto st0
tr189:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st180
	st180:
		if p++; p == pe {
			goto _test_eof180
		}
	st_case_180:
//line foreign_key_parser.go:3646
		switch data[p] {
		case 65:
			goto tr87
		case 97:
			goto tr87
		}
		goto st0
tr85:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st181
	st181:
		if p++; p == pe {
			goto _test_eof181
		}
	st_case_181:
//line foreign_key_parser.go:3665
		switch data[p] {
		case 73:
			goto tr190
		case 105:
			goto tr190
		}
		goto st0
tr190:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st182
	st182:
		if p++; p == pe {
			goto _test_eof182
		}
	st_case_182:
//line foreign_key_parser.go:3684
		switch data[p] {
		case 77:
			goto tr191
		case 109:
			goto tr191
		}
		goto st0
tr191:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st183
	st183:
		if p++; p == pe {
			goto _test_eof183
		}
	st_case_183:
//line foreign_key_parser.go:3703
		switch data[p] {
		case 80:
			goto tr192
		case 112:
			goto tr192
		}
		goto st0
tr192:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st184
	st184:
		if p++; p == pe {
			goto _test_eof184
		}
	st_case_184:
//line foreign_key_parser.go:3722
		switch data[p] {
		case 76:
			goto tr193
		case 108:
			goto tr193
		}
		goto st0
tr193:
//line foreign_key_parser.rl:22

		buffer.WriteByte(data[p])
	
	goto st185
	st185:
		if p++; p == pe {
			goto _test_eof185
		}
	st_case_185:
//line foreign_key_parser.go:3741
		switch data[p] {
		case 69:
			goto tr88
		case 101:
			goto tr88
		}
		goto st0
	st_out:
	_test_eof1: cs = 1; goto _test_eof
	_test_eof2: cs = 2; goto _test_eof
	_test_eof3: cs = 3; goto _test_eof
	_test_eof4: cs = 4; goto _test_eof
	_test_eof5: cs = 5; goto _test_eof
	_test_eof6: cs = 6; goto _test_eof
	_test_eof7: cs = 7; goto _test_eof
	_test_eof8: cs = 8; goto _test_eof
	_test_eof9: cs = 9; goto _test_eof
	_test_eof10: cs = 10; goto _test_eof
	_test_eof11: cs = 11; goto _test_eof
	_test_eof12: cs = 12; goto _test_eof
	_test_eof13: cs = 13; goto _test_eof
	_test_eof14: cs = 14; goto _test_eof
	_test_eof15: cs = 15; goto _test_eof
	_test_eof16: cs = 16; goto _test_eof
	_test_eof17: cs = 17; goto _test_eof
	_test_eof18: cs = 18; goto _test_eof
	_test_eof19: cs = 19; goto _test_eof
	_test_eof20: cs = 20; goto _test_eof
	_test_eof21: cs = 21; goto _test_eof
	_test_eof22: cs = 22; goto _test_eof
	_test_eof23: cs = 23; goto _test_eof
	_test_eof24: cs = 24; goto _test_eof
	_test_eof25: cs = 25; goto _test_eof
	_test_eof26: cs = 26; goto _test_eof
	_test_eof27: cs = 27; goto _test_eof
	_test_eof28: cs = 28; goto _test_eof
	_test_eof29: cs = 29; goto _test_eof
	_test_eof30: cs = 30; goto _test_eof
	_test_eof31: cs = 31; goto _test_eof
	_test_eof32: cs = 32; goto _test_eof
	_test_eof33: cs = 33; goto _test_eof
	_test_eof186: cs = 186; goto _test_eof
	_test_eof187: cs = 187; goto _test_eof
	_test_eof34: cs = 34; goto _test_eof
	_test_eof35: cs = 35; goto _test_eof
	_test_eof36: cs = 36; goto _test_eof
	_test_eof37: cs = 37; goto _test_eof
	_test_eof38: cs = 38; goto _test_eof
	_test_eof39: cs = 39; goto _test_eof
	_test_eof40: cs = 40; goto _test_eof
	_test_eof41: cs = 41; goto _test_eof
	_test_eof42: cs = 42; goto _test_eof
	_test_eof43: cs = 43; goto _test_eof
	_test_eof188: cs = 188; goto _test_eof
	_test_eof44: cs = 44; goto _test_eof
	_test_eof45: cs = 45; goto _test_eof
	_test_eof46: cs = 46; goto _test_eof
	_test_eof47: cs = 47; goto _test_eof
	_test_eof48: cs = 48; goto _test_eof
	_test_eof49: cs = 49; goto _test_eof
	_test_eof50: cs = 50; goto _test_eof
	_test_eof51: cs = 51; goto _test_eof
	_test_eof52: cs = 52; goto _test_eof
	_test_eof53: cs = 53; goto _test_eof
	_test_eof54: cs = 54; goto _test_eof
	_test_eof55: cs = 55; goto _test_eof
	_test_eof56: cs = 56; goto _test_eof
	_test_eof57: cs = 57; goto _test_eof
	_test_eof58: cs = 58; goto _test_eof
	_test_eof59: cs = 59; goto _test_eof
	_test_eof60: cs = 60; goto _test_eof
	_test_eof189: cs = 189; goto _test_eof
	_test_eof61: cs = 61; goto _test_eof
	_test_eof62: cs = 62; goto _test_eof
	_test_eof63: cs = 63; goto _test_eof
	_test_eof64: cs = 64; goto _test_eof
	_test_eof65: cs = 65; goto _test_eof
	_test_eof66: cs = 66; goto _test_eof
	_test_eof67: cs = 67; goto _test_eof
	_test_eof68: cs = 68; goto _test_eof
	_test_eof69: cs = 69; goto _test_eof
	_test_eof70: cs = 70; goto _test_eof
	_test_eof71: cs = 71; goto _test_eof
	_test_eof72: cs = 72; goto _test_eof
	_test_eof73: cs = 73; goto _test_eof
	_test_eof74: cs = 74; goto _test_eof
	_test_eof75: cs = 75; goto _test_eof
	_test_eof76: cs = 76; goto _test_eof
	_test_eof77: cs = 77; goto _test_eof
	_test_eof190: cs = 190; goto _test_eof
	_test_eof191: cs = 191; goto _test_eof
	_test_eof78: cs = 78; goto _test_eof
	_test_eof79: cs = 79; goto _test_eof
	_test_eof80: cs = 80; goto _test_eof
	_test_eof81: cs = 81; goto _test_eof
	_test_eof82: cs = 82; goto _test_eof
	_test_eof83: cs = 83; goto _test_eof
	_test_eof84: cs = 84; goto _test_eof
	_test_eof85: cs = 85; goto _test_eof
	_test_eof86: cs = 86; goto _test_eof
	_test_eof87: cs = 87; goto _test_eof
	_test_eof88: cs = 88; goto _test_eof
	_test_eof89: cs = 89; goto _test_eof
	_test_eof90: cs = 90; goto _test_eof
	_test_eof91: cs = 91; goto _test_eof
	_test_eof92: cs = 92; goto _test_eof
	_test_eof93: cs = 93; goto _test_eof
	_test_eof94: cs = 94; goto _test_eof
	_test_eof95: cs = 95; goto _test_eof
	_test_eof96: cs = 96; goto _test_eof
	_test_eof97: cs = 97; goto _test_eof
	_test_eof98: cs = 98; goto _test_eof
	_test_eof99: cs = 99; goto _test_eof
	_test_eof100: cs = 100; goto _test_eof
	_test_eof101: cs = 101; goto _test_eof
	_test_eof102: cs = 102; goto _test_eof
	_test_eof103: cs = 103; goto _test_eof
	_test_eof104: cs = 104; goto _test_eof
	_test_eof105: cs = 105; goto _test_eof
	_test_eof192: cs = 192; goto _test_eof
	_test_eof193: cs = 193; goto _test_eof
	_test_eof106: cs = 106; goto _test_eof
	_test_eof107: cs = 107; goto _test_eof
	_test_eof108: cs = 108; goto _test_eof
	_test_eof109: cs = 109; goto _test_eof
	_test_eof110: cs = 110; goto _test_eof
	_test_eof111: cs = 111; goto _test_eof
	_test_eof112: cs = 112; goto _test_eof
	_test_eof113: cs = 113; goto _test_eof
	_test_eof114: cs = 114; goto _test_eof
	_test_eof115: cs = 115; goto _test_eof
	_test_eof116: cs = 116; goto _test_eof
	_test_eof117: cs = 117; goto _test_eof
	_test_eof118: cs = 118; goto _test_eof
	_test_eof119: cs = 119; goto _test_eof
	_test_eof120: cs = 120; goto _test_eof
	_test_eof121: cs = 121; goto _test_eof
	_test_eof194: cs = 194; goto _test_eof
	_test_eof195: cs = 195; goto _test_eof
	_test_eof122: cs = 122; goto _test_eof
	_test_eof123: cs = 123; goto _test_eof
	_test_eof124: cs = 124; goto _test_eof
	_test_eof125: cs = 125; goto _test_eof
	_test_eof126: cs = 126; goto _test_eof
	_test_eof127: cs = 127; goto _test_eof
	_test_eof128: cs = 128; goto _test_eof
	_test_eof129: cs = 129; goto _test_eof
	_test_eof130: cs = 130; goto _test_eof
	_test_eof131: cs = 131; goto _test_eof
	_test_eof132: cs = 132; goto _test_eof
	_test_eof133: cs = 133; goto _test_eof
	_test_eof134: cs = 134; goto _test_eof
	_test_eof135: cs = 135; goto _test_eof
	_test_eof136: cs = 136; goto _test_eof
	_test_eof137: cs = 137; goto _test_eof
	_test_eof138: cs = 138; goto _test_eof
	_test_eof139: cs = 139; goto _test_eof
	_test_eof140: cs = 140; goto _test_eof
	_test_eof141: cs = 141; goto _test_eof
	_test_eof142: cs = 142; goto _test_eof
	_test_eof143: cs = 143; goto _test_eof
	_test_eof144: cs = 144; goto _test_eof
	_test_eof145: cs = 145; goto _test_eof
	_test_eof146: cs = 146; goto _test_eof
	_test_eof147: cs = 147; goto _test_eof
	_test_eof148: cs = 148; goto _test_eof
	_test_eof149: cs = 149; goto _test_eof
	_test_eof150: cs = 150; goto _test_eof
	_test_eof151: cs = 151; goto _test_eof
	_test_eof152: cs = 152; goto _test_eof
	_test_eof153: cs = 153; goto _test_eof
	_test_eof154: cs = 154; goto _test_eof
	_test_eof155: cs = 155; goto _test_eof
	_test_eof156: cs = 156; goto _test_eof
	_test_eof157: cs = 157; goto _test_eof
	_test_eof158: cs = 158; goto _test_eof
	_test_eof159: cs = 159; goto _test_eof
	_test_eof160: cs = 160; goto _test_eof
	_test_eof161: cs = 161; goto _test_eof
	_test_eof162: cs = 162; goto _test_eof
	_test_eof163: cs = 163; goto _test_eof
	_test_eof164: cs = 164; goto _test_eof
	_test_eof165: cs = 165; goto _test_eof
	_test_eof166: cs = 166; goto _test_eof
	_test_eof167: cs = 167; goto _test_eof
	_test_eof168: cs = 168; goto _test_eof
	_test_eof169: cs = 169; goto _test_eof
	_test_eof170: cs = 170; goto _test_eof
	_test_eof171: cs = 171; goto _test_eof
	_test_eof172: cs = 172; goto _test_eof
	_test_eof173: cs = 173; goto _test_eof
	_test_eof174: cs = 174; goto _test_eof
	_test_eof175: cs = 175; goto _test_eof
	_test_eof176: cs = 176; goto _test_eof
	_test_eof177: cs = 177; goto _test_eof
	_test_eof178: cs = 178; goto _test_eof
	_test_eof179: cs = 179; goto _test_eof
	_test_eof180: cs = 180; goto _test_eof
	_test_eof181: cs = 181; goto _test_eof
	_test_eof182: cs = 182; goto _test_eof
	_test_eof183: cs = 183; goto _test_eof
	_test_eof184: cs = 184; goto _test_eof
	_test_eof185: cs = 185; goto _test_eof

	_test_eof: {}
	if p == eof {
		switch cs {
		case 190:
//line foreign_key_parser.rl:34

		fk.setMatch(buffer.String())
		buffer.Reset()
	
		case 192:
//line foreign_key_parser.rl:38

		fk.setOnDelete(buffer.String())
		buffer.Reset()
	
		case 194:
//line foreign_key_parser.rl:42

		fk.setOnUpdate(buffer.String())
		buffer.Reset()
	
//line foreign_key_parser.go:3967
		}
	}

	_out: {}
	}

//line foreign_key_parser.rl:82


	if cs < foreign_key_first_final {
		return nil, &parseError{
		    cs: cs,
		    data: data,
		}
	}

	return fk, nil
}
